# This file serves as a template file for the pegen parser generator
# It contains double-underscore placeholders that are dynamically replaced
# during code generation to produce a runnable parser implementation

# Everything before the "__START_FILE__" marker are ignored in the final parser

# __START_FILE__

# Auto-generated by vcs/pegen.py from __FILENAME__
# To regenerate this, `cd` to the top directory of this project and run:
# `$python -m vcs.pegen __FILENAME__ -o __OUTPUT__`

import time

from functools import wraps
from typing import Any, Callable, ClassVar, cast

from vcs import ast
from vcs import errors as err
from vcs import lexer as lex
from vcs import utils
# __SUBHEADER__

type Mark = int

def _get_indent_closure() -> Callable[[int], str]:
    _INDENT_CACHE = {}

    def get_indent(level: int) -> str:
        if level not in _INDENT_CACHE:
            _INDENT_CACHE[level] = "  " * level
        return _INDENT_CACHE[level]

    return get_indent

_get_indent = _get_indent_closure()
del _get_indent_closure


def logger[F: Callable[..., Any], P: __CLASS_NAME__](method: F) -> F:
    """
    Logging decorator for non-memoized parser methods.
    """
    method_name = method.__name__

    @wraps(method)
    def logger_wrapper(self: P, *args: object) -> Any:
        if not self.dump_tree:
            return method(self, *args)

        level = self._level
        fill = _get_indent(level)

        args_repr = ",".join(repr(arg) for arg in args)
        peek_repr = repr(self._showpeek())

        utils.print_info(f"{fill}{method_name}({args_repr}) .... (looking at {peek_repr})")

        self._level = level + 1
        try:
            tree = method(self, *args)
        finally:
            self._level = level

        tree_repr = repr(tree)[:80]
        utils.print_info(f"{fill}... {method_name}({args_repr}) --> {tree_repr}")
        return tree

    return cast(F, logger_wrapper)


def memoize[F: Callable[..., Any], P: __CLASS_NAME__](method: F) -> F:
    """
    Memoization decorator for parser methods.
    """
    method_name = method.__name__

    @wraps(method)
    def memoize_wrapper(self: P, *args: object) -> Any:
        cache = self._cache
        mark = self._mark()
        key = (mark, method_name, args)

        # fast path
        if not self.dump_tree:
            try:
                tree, endmark = cache[key]
                self._reset(endmark)
                return tree
            except KeyError:
                pass  # continue with slow path
        else:
            # debug path
            cached = cache.get(key)
            if cached is not None:
                tree, endmark = cached
                self._reset(endmark)
                fill = _get_indent(self._level)
                args_repr = ",".join(repr(arg) for arg in args)
                tree_repr = repr(tree)[:80]
                utils.print_info(f"{fill}{method_name}({args_repr}) -> {tree_repr}")
                return tree

        # slow path
        level = self._level

        if self.dump_tree:
            fill = _get_indent(level)
            args_repr = ",".join(repr(arg) for arg in args)
            peek_repr = repr(self._showpeek())
            utils.print_info(f"{fill}{method_name}({args_repr}) ... (looking at {peek_repr})")

        self._level = level + 1
        try:
            tree = method(self, *args)
        finally:
            self._level = level

        endmark = self._mark()
        cache[key] = (tree, endmark)

        if self.dump_tree:
            tree_repr = repr(tree)[:80]
            utils.print_info(f"{fill}... {method_name}({args_repr}) -> {tree_repr}")  # type: ignore

        return tree

    return cast(F, memoize_wrapper)


def memoize_left_rec[P: __CLASS_NAME__, T](
    method: Callable[[P], T | None],
) -> Callable[[P], T | None]:
    """
    Memoization for left-recursive grammar rules.
    """
    method_name = method.__name__

    @wraps(method)
    def memoize_left_rec_wrapper(self: P) -> T | None:
        cache = self._cache
        mark = self._mark()
        key = (mark, method_name, ())

        # fast path
        if not self.dump_tree:
            try:
                tree, endmark = cache[key]
                if tree is not None:
                    self._reset(endmark)
                return tree
            except KeyError:
                pass
        else:
            cached = cache.get(key)
            if cached is not None:
                tree, endmark = cached
                if tree is not None:
                    self._reset(endmark)
                fill = _get_indent(self._level)
                tree_repr = repr(tree)[:80] if tree else "None"
                utils.print_info(f"{fill}{method_name}() -> {tree_repr} [fresh]")
                return tree

        # For left-recursive rules we manipulate the cache and
        # loop until the rule shows no progress, then pick the
        # previous result. For an explanation why this works, see
        # https://github.com/PhilippeSigaud/Pegged/wiki/Left-Recursion
        # (But we use the memoization cache instead of a static
        # variable; perhaps this is similar to a paper by Warth et al
        # (http://web.cs.ucla.edu/~todd/research/pub.php?id=pepm08)

        level = self._level
        fill = _get_indent(level) if self.dump_tree else ""

        if self.dump_tree:
            peek_repr = repr(self._showpeek())
            utils.print_info(f"{fill}{method_name} ... (looking at {peek_repr})")
            utils.print_info(f"{fill}Recursive {method_name} at {mark} depth 0")

        cache[key] = (None, mark)
        lastresult: T | None = None
        lastmark = mark
        depth = 0

        self._level = level + 1
        try:
            while True:
                self._reset(mark)
                self._in_recursive_rule += 1
                try:
                    result = method(self)
                finally:
                    self._in_recursive_rule -= 1

                endmark = self._mark()
                depth += 1

                if self.dump_tree:
                    result_repr = repr(result)[:80] if result else "None"
                    utils.print_info(
                        f"{fill}Recursive {method_name} at {mark} depth {depth}: {result_repr} to {endmark}"
                    )

                if not result:
                    if self.dump_tree:
                        last_repr = repr(lastresult)[:80] if lastresult else "None"
                        utils.print_info(f"{fill}Fail with {last_repr} to {lastmark}")
                    break

                if endmark <= lastmark:
                    if self.dump_tree:
                        last_repr = repr(lastresult)[:80] if lastresult else "None"
                        utils.print_info(f"{fill}Bailing with {last_repr} to {lastmark}")
                    break

                cache[key] = (result, endmark)
                lastresult, lastmark = result, endmark
        finally:
            self._level = level

        self._reset(lastmark)
        tree = lastresult

        if self.dump_tree:
            tree_repr = repr(tree)[:80] if tree else "None"
            utils.print_info(f"{fill}{method_name}() -> {tree_repr} [cached]")

        if tree is not None:
            endmark = self._mark()
        else:
            endmark = mark
            self._reset(endmark)

        cache[key] = (tree, endmark)
        return tree

    return memoize_left_rec_wrapper


class TokenStream:
    """
    A small lookahead/rewind wrapper around a Lexer iterator.
    Keeps tokens in a buffer so callers can peek, getnext, mark/reset etc.
    """

    def __init__(self, lexer: lex.Lexer):
        self.filename = lexer.filename
        self.source = lexer.source
        self.source_lines = lexer.source_lines
        self.report = lexer.report

        self._lexer = lexer
        self._tokgen = iter(lexer)
        self._tokens: list[lex.TokenInfo] = []
        self._index: int = 0

    def get_error_info_on(self, token: lex.TokenInfo | None):
        if token is None:
            token = self._tokens[self._index - 1]
        return self._lexer.get_error_info(len(token.value), token.lexpos)

    def get_error_info_range(self, start_tok: lex.TokenInfo, end_tok: lex.TokenInfo):
        return self._lexer.get_error_info(
            end_tok.lexpos + len(end_tok.value) - start_tok.lexpos,
            start_tok.lexpos,
        )

    def getnext(self) -> lex.TokenInfo:
        tok = self.peek()
        self._index += 1
        return tok

    def peek(self) -> lex.TokenInfo:
        while self._index == len(self._tokens):
            tok = next(self._tokgen)
            self._tokens.append(tok)
        return self._tokens[self._index]

    def diagnose(self) -> lex.TokenInfo:
        if not self._tokens:
            self.getnext()
        return self._tokens[-1]

    def last_nonblank_token(self) -> lex.TokenInfo:
        for tok in reversed(self._tokens[:self._index]):
            if tok.type not in [
                lex.TokenType.ENDMARKER,
                lex.TokenType.NEWLINE,
                lex.TokenType.INDENT,
                lex.TokenType.DEDENT,
                lex.TokenType.ERRORTOKEN,
            ]:
                break
        return tok  # type: ignore

    def mark(self) -> Mark:
        return self._index

    def reset(self, index: Mark) -> None:
        if index == self._index:
            return
        assert 0 <= index <= len(self._tokens), (index, len(self._tokens))
        self._index = index


class __CLASS_NAME__:
    """
    The main parser class.
    """

    KEYWORDS: ClassVar[tuple[str, ...]]
    SOFT_KEYWORDS: ClassVar[tuple[str, ...]]

    def __init__(
        self,
        lexer: lex.Lexer,
        errors: err.ErrorCollector,
        dump_tree=False,
        dump_ast=False,
        parse_stats=False,
    ):
        tokenstream = TokenStream(lexer)
        self._tokenstream = tokenstream

        self.filename = tokenstream.filename
        self.diagnose = tokenstream.diagnose
        self.errors = errors

        # Debug flags
        self.dump_tree = dump_tree
        self.dump_ast = dump_ast
        self.parse_stats = parse_stats

        self._mark = tokenstream.mark
        self._reset = tokenstream.reset
        self._peek = tokenstream.peek
        self._getnext = tokenstream.getnext
        self._last_nonblank_token = tokenstream.last_nonblank_token
        self._source = tokenstream.source
        self._source_lines = tokenstream.source_lines

        self._call_invalid_rules = True
        self._level = 0
        self._cache: dict[tuple[Mark, str, tuple[Any, ...]], tuple[Any, Mark]] = {}
        self._in_recursive_rule = 0

    def _showpeek(self) -> str:
        # Brief token display
        token = self._peek()
        return f"{token.lineno}.{token.column}: {token.type}:{
            token.value if len(token.value) <= 64 else token.value[:64] + '...'
        }"

    @memoize
    def _accept(self, token_type: lex.TokenType | str) -> lex.TokenInfo | None:
        # Accept a token of the given type or value; returns the lex.TokenInfo or None
        mark = self._mark()
        try:
            tok = self._getnext()
        except StopIteration:
            return None
            
        if tok.type == token_type:
            if token_type == lex.TokenType.NAME and tok.value in self.KEYWORDS:
                return None
            return tok    
        if tok.type == lex.TokenType.NAME and tok.value == token_type:
            return tok
        if tok.type == lex.TokenType.OP and tok.value == token_type:
            return tok
        if (
            tok.type == lex.TokenType.NAME
            and token_type == "SOFT_KEYWORD"
            and tok.value in self.SOFT_KEYWORDS
        ):
            return tok
        
        self._reset(mark)

    def _expect(self, res: Any, expectation: lex.TokenType | str) -> lex.TokenInfo | None:
        # Ensure that a previous _accept returned a result, otherwise report an error
        if res is None:
            string = expectation.name.lower() if isinstance(expectation, lex.TokenType) else expectation
            self.report(err.ExpectationFailed(self.get_error_info_on(), string))
        return res

    def _positive_lookahead[T](self, func: Callable[..., T], *args: object) -> T:
        # Run func in lookahead mode: succeed/fail but do not consume tokens
        mark = self._mark()
        ok = func(*args)
        self._reset(mark)
        return ok

    def _negative_lookahead(self, func: Callable[..., object], *args: object) -> bool:
        # Run func in negative lookahead mode: succeed only if func would fail
        mark = self._mark()
        ok = func(*args)
        self._reset(mark)
        return not ok

    def report(self, error: err.CompilerError):
        self.errors.add(error)

    def get_error_info_on(self, node: ast.ASTNode | lex.TokenInfo | None = None) -> err.ErrorInfo:
        if isinstance(node, lex.TokenInfo) or node is None:
            return self._tokenstream.get_error_info_on(node)
        
        return err.ErrorInfo(
            node.filename,
            node.lineno,
            node.column,
            self._source,
            node.end_lineno,
            node.end_column,
        )

    def get_error_info_between(
        self,
        start_node: ast.ASTNode | lex.TokenInfo,
        end_node: ast.ASTNode | lex.TokenInfo,
    ) -> err.ErrorInfo:
        """
        Report an error where the start and end locations are known.
        """
        start_lineno, start_column = start_node.lineno, start_node.column
        end_lineno, end_column = end_node.end_lineno, end_node.end_column
        return err.ErrorInfo(start_node.filename, start_lineno, start_column, self._source, end_lineno, end_column)

    def get_error_info_starting_from(self, node: ast.ASTNode | lex.TokenInfo) -> err.ErrorInfo:
        return self.get_error_info_between(node, self._tokenstream.diagnose())

    def get_error_info_next_token(self) -> err.ErrorInfo:
        return self.get_error_info_on(self._peek())
    
    def parse(self):
        t0 = time.time()
        tree = self._start() or __FALLBACK__  # type: ignore
        t1 = time.time()

        if self.dump_ast:
            utils.print_info(utils.dump_astnode(tree))
        
        if self.parse_stats:
            dt = t1 - t0
            tokenstream = self._tokenstream
            nlines = tokenstream._lexer.linecount

            info1 = f"Total time: {dt:.3f} sec; {nlines} lines"
            if dt:
                info1 += f"; {nlines / dt:.0f} lines/sec"
            
            utils.print_info(info1)
            utils.print_info("Caches sizes:")
            utils.print_info(f"  token array : {len(tokenstream._tokens):10}")
            utils.print_info(f"        cache : {len(self._cache):10}")
        
        return tree

    # __PARSER_CODE__


if __name__ == "__main__":
    from vcs.cli import cli
    cli()
