# Auto-generated by vcs/pegen.py from vcs/vcs.gram
# To regenerate this, `cd` to the top directory of this project and run:
# `$python -m vcs.pegen vcs/vcs.gram -o vcs/parser.py`

from typing import Any, Callable, ClassVar, cast
from functools import wraps

from vcs.errors import *
from vcs.lexer import Lexer, TokenInfo, TokenType

from vcs.astnodes import *


type Mark = int

def _get_indent_closure() -> Callable[[int], str]:
    _INDENT_CACHE = {}

    def get_indent(level: int) -> str:
        if level not in _INDENT_CACHE:
            _INDENT_CACHE[level] = "  " * level
        return _INDENT_CACHE[level]

    return get_indent

_get_indent = _get_indent_closure()
del _get_indent_closure


def logger[F: Callable[..., Any], P: Parser](method: F) -> F:
    """
    logging decorator for non-memoized parser methods
    """
    method_name = method.__name__

    @wraps(method)
    def logger_wrapper(self: P, *args: object) -> Any:
        if not self.verbose:
            return method(self, *args)

        level = self._level
        fill = _get_indent(level)

        args_repr = ",".join(repr(arg) for arg in args)
        peek_repr = repr(self._showpeek())

        print(f"{fill}{method_name}({args_repr}) .... (looking at {peek_repr})\n")

        self._level = level + 1
        try:
            tree = method(self, *args)
        finally:
            self._level = level

        tree_repr = repr(tree)[:80]
        print(f"{fill}... {method_name}({args_repr}) --> {tree_repr}\n")
        return tree

    return cast(F, logger_wrapper)


def memoize[F: Callable[..., Any], P: Parser](method: F) -> F:
    """
    memoization decorator for parser methods
    """
    method_name = method.__name__

    @wraps(method)
    def memoize_wrapper(self: P, *args: object) -> Any:
        cache = self._cache
        mark = self._mark()
        key = (mark, method_name, args)

        # fast path
        if not self.verbose:
            try:
                tree, endmark = cache[key]
                self._reset(endmark)
                return tree
            except KeyError:
                pass  # continue with slow path
        else:
            # debug path
            cached = cache.get(key)
            if cached is not None:
                tree, endmark = cached
                self._reset(endmark)
                fill = _get_indent(self._level)
                args_repr = ",".join(repr(arg) for arg in args)
                tree_repr = repr(tree)[:80]
                print(f"{fill}{method_name}({args_repr}) -> {tree_repr}\n")
                return tree

        # slow path
        level = self._level

        if self.verbose:
            fill = _get_indent(level)
            args_repr = ",".join(repr(arg) for arg in args)
            peek_repr = repr(self._showpeek())
            print(f"{fill}{method_name}({args_repr}) ... (looking at {peek_repr})\n")

        self._level = level + 1
        try:
            tree = method(self, *args)
        finally:
            self._level = level

        endmark = self._mark()
        cache[key] = (tree, endmark)

        if self.verbose:
            tree_repr = repr(tree)[:80]
            print(f"{fill}... {method_name}({args_repr}) -> {tree_repr}\n")  # type: ignore

        return tree

    return cast(F, memoize_wrapper)


def memoize_left_rec[P: Parser, T](
    method: Callable[[P], T | None],
) -> Callable[[P], T | None]:
    """
    memoization for left-recursive grammar rules
    """
    method_name = method.__name__

    @wraps(method)
    def memoize_left_rec_wrapper(self: P) -> T | None:
        cache = self._cache
        mark = self._mark()
        key = (mark, method_name, ())

        # fast path
        if not self.verbose:
            try:
                tree, endmark = cache[key]
                if tree is not None:
                    self._reset(endmark)
                return tree
            except KeyError:
                pass
        else:
            cached = cache.get(key)
            if cached is not None:
                tree, endmark = cached
                if tree is not None:
                    self._reset(endmark)
                fill = _get_indent(self._level)
                tree_repr = repr(tree)[:80] if tree else "None"
                print(f"{fill}{method_name}() -> {tree_repr} [fresh]\n")
                return tree

        # For left-recursive rules we manipulate the cache and
        # loop until the rule shows no progress, then pick the
        # previous result. For an explanation why this works, see
        # https://github.com/PhilippeSigaud/Pegged/wiki/Left-Recursion
        # (But we use the memoization cache instead of a static
        # variable; perhaps this is similar to a paper by Warth et al
        # (http://web.cs.ucla.edu/~todd/research/pub.php?id=pepm08)

        level = self._level
        fill = _get_indent(level) if self.verbose else ""

        if self.verbose:
            peek_repr = repr(self._showpeek())
            print(f"{fill}{method_name} ... (looking at {peek_repr})\n")
            print(f"{fill}Recursive {method_name} at {mark} depth 0\n")

        cache[key] = (None, mark)
        lastresult: T | None = None
        lastmark = mark
        depth = 0

        self._level = level + 1
        try:
            while True:
                self._reset(mark)
                self._in_recursive_rule += 1
                try:
                    result = method(self)
                finally:
                    self._in_recursive_rule -= 1

                endmark = self._mark()
                depth += 1

                if self.verbose:
                    result_repr = repr(result)[:80] if result else "None"
                    print(
                        f"{fill}Recursive {method_name} at {mark} depth {depth}: "
                        f"{result_repr} to {endmark}\n"
                    )

                if not result:
                    if self.verbose:
                        last_repr = repr(lastresult)[:80] if lastresult else "None"
                        print(f"{fill}Fail with {last_repr} to {lastmark}\n")
                    break

                if endmark <= lastmark:
                    if self.verbose:
                        last_repr = repr(lastresult)[:80] if lastresult else "None"
                        print(f"{fill}Bailing with {last_repr} to {lastmark}\n")
                    break

                cache[key] = (result, endmark)
                lastresult, lastmark = result, endmark
        finally:
            self._level = level

        self._reset(lastmark)
        tree = lastresult

        if self.verbose:
            tree_repr = repr(tree)[:80] if tree else "None"
            print(f"{fill}{method_name}() -> {tree_repr} [cached]\n")

        if tree is not None:
            endmark = self._mark()
        else:
            endmark = mark
            self._reset(endmark)

        cache[key] = (tree, endmark)
        return tree

    return memoize_left_rec_wrapper


class TokenStream:
    """
    A small lookahead/rewind wrapper around a Lexer iterator
    Keeps tokens in a buffer so callers can peek, getnext, mark/reset etc
    """

    def __init__(self, lexer: Lexer):
        self.filename = lexer.filename
        self.source = lexer.source
        self.source_lines = lexer.source_lines
        self.report = lexer.report

        self._lexer = lexer
        self._tokgen = iter(lexer)
        self._tokens: list[TokenInfo] = []
        self._index: int = 0

    def get_error_info_on(self, token: TokenInfo | None):
        if token is None:
            token = self._tokens[self._index - 1]
        return self._lexer.get_error_info(len(token.value), token.lexpos)

    def get_error_info_range(self, start_tok: TokenInfo, end_tok: TokenInfo):
        return self._lexer.get_error_info(
            end_tok.lexpos + len(end_tok.value) - start_tok.lexpos,
            start_tok.lexpos,
        )

    def getnext(self) -> TokenInfo:
        tok = self.peek()
        self._index += 1
        return tok

    def peek(self) -> TokenInfo:
        while self._index == len(self._tokens):
            tok = next(self._tokgen)
            self._tokens.append(tok)
        return self._tokens[self._index]

    def diagnose(self) -> TokenInfo:
        if not self._tokens:
            self.getnext()
        return self._tokens[-1]

    def last_nonblank_token(self) -> TokenInfo:
        for tok in reversed(self._tokens[:self._index]):
            if tok.type not in [
                TokenType.ENDMARKER,
                TokenType.NEWLINE,
                TokenType.INDENT,
                TokenType.DEDENT,
                TokenType.ERRORTOKEN,
            ]:
                break
        return tok  # type: ignore

    def mark(self) -> Mark:
        return self._index

    def reset(self, index: Mark) -> None:
        if index == self._index:
            return
        assert 0 <= index <= len(self._tokens), (index, len(self._tokens))
        self._index = index


class Parser:
    """
    The main parser class
    """

    KEYWORDS: ClassVar[tuple[str, ...]]
    SOFT_KEYWORDS: ClassVar[tuple[str, ...]]

    def __init__(self, lexer: Lexer, errors: ErrorCollector, skip_comments=False, verbose=False):
        tokenstream = TokenStream(lexer)
        self._tokenstream = tokenstream

        self.filename = tokenstream.filename
        self.diagnose = tokenstream.diagnose
        self.errors = errors
        self.skip_comments = skip_comments
        self.verbose = verbose

        self._mark = tokenstream.mark
        self._reset = tokenstream.reset
        self._peek = tokenstream.peek
        self._getnext = tokenstream.getnext
        self._last_nonblank_token = tokenstream.last_nonblank_token
        self._source = tokenstream.source
        self._source_lines = tokenstream.source_lines

        self._call_invalid_rules = True
        self._level = 0
        self._cache: dict[tuple[Mark, str, tuple[Any, ...]], tuple[Any, Mark]] = {}
        self._in_recursive_rule = 0

    def _showpeek(self) -> str:
        # Brief token display
        token = self._peek()
        return f"{token.lineno}.{token.column}: {token.type}:{
            token.value if len(token.value) <= 64 else token.value[:64] + '...'
        }"

    @memoize
    def _accept(self, token_type: TokenType | str) -> TokenInfo | None:
        # Accept a token of the given type or value; returns the TokenInfo or None
        while True:
            mark = self._mark()
            try:
                tok = self._getnext()
            except StopIteration:
                return None

            if not (self.skip_comments and tok.type == TokenType.COMMENT):
                break
            
        if tok.type == token_type:
            if token_type == TokenType.NAME and tok.value in self.KEYWORDS:
                return None
            return tok    
        if tok.type == TokenType.NAME and tok.value == token_type:
            return tok
        if tok.type == TokenType.OP and tok.value == token_type:
            return tok
        if (
            tok.type == TokenType.NAME
            and token_type == "SOFT_KEYWORD"
            and tok.value in self.SOFT_KEYWORDS
        ):
            return tok
        
        self._reset(mark)

    def _expect(self, res: Any, expectation: TokenType | str) -> TokenInfo | None:
        # Ensure that a previous _accept returned a result, otherwise report an error
        if res is None:
            string = expectation.name.lower() if isinstance(expectation, TokenType) else expectation
            self.report(ExpectationFailed(self.get_error_info_on(), string))
        return res

    def _positive_lookahead[T](self, func: Callable[..., T], *args: object) -> T:
        # Run func in lookahead mode: succeed/fail but do not consume tokens
        mark = self._mark()
        ok = func(*args)
        self._reset(mark)
        return ok

    def _negative_lookahead(self, func: Callable[..., object], *args: object) -> bool:
        # Run func in negative lookahead mode: succeed only if func would fail
        mark = self._mark()
        ok = func(*args)
        self._reset(mark)
        return not ok

    def report(self, error: CompilerError):
        self.errors.add(error)

    def get_error_info_on(self, node: ASTNode | TokenInfo | None = None) -> ErrorInfo:
        if isinstance(node, TokenInfo) or node is None:
            return self._tokenstream.get_error_info_on(node)
        
        return ErrorInfo(
            node.filename,
            node.lineno,
            node.column,
            self._source,
            node.end_lineno,
            node.end_column,
        )

    def get_error_info_between(
        self,
        start_node: ASTNode | TokenInfo,
        end_node: ASTNode | TokenInfo,
    ) -> ErrorInfo:
        """
        Report an error where the start and end locations are known
        """
        start_lineno, start_column = start_node.lineno, start_node.column

        if isinstance(end_node, TokenInfo):
            end_lineno, end_column = end_node.get_endpos()
        else:
            end_lineno, end_column = end_node.end_lineno, end_node.end_column

        return ErrorInfo(start_node.filename, start_lineno, start_column, self._source, end_lineno, end_column)

    def get_error_info_starting_from(self, node: ASTNode | TokenInfo) -> ErrorInfo:
        return self.get_error_info_between(node, self._tokenstream.diagnose())

    def get_error_info_next_token(self) -> ErrorInfo:
        return self.get_error_info_on(self._peek())
    
    def parse(self):
        return self._start() or [Module(body=[]), self.report(ParseError(self.get_error_info_on(self.diagnose())))][0]

    @memoize
    def _start(self) -> Module | None:
        # start: module $
        mark = self._mark()
        if (
            (m := self._module())
            and
            (self._accept(TokenType.ENDMARKER))
        ):
            return m
        self._reset(mark)
        return None

    @memoize
    def _module(self) -> Module | None:
        # module: toplevel+
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (f := self._loop1_1())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Module(body=f, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _toplevel(self) -> FunctionDeclaration | Comment | None:
        # toplevel: func_decl | comment
        mark = self._mark()
        if (
            (func_decl := self._func_decl())
        ):
            return func_decl
        self._reset(mark)
        if (
            (comment := self._comment())
        ):
            return comment
        self._reset(mark)
        return None

    @memoize
    def _func_decl(self) -> FunctionDeclaration | None:
        # func_decl: NAME '(' params? ')' '->' type ':' block | NAME '(' params? ')' ':' block
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (n := self._accept(TokenType.NAME))
            and
            (lp := self._accept('('))
            and
            (p := self._params(),)
            and
            (rp := self._accept(')'))
            and
            (arr := self._accept('->'))
            and
            (t := self._type())
            and
            (cln := self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return FunctionDeclaration(name_token=n, lparen_token=lp, params=p or [], rparen_token=rp, arrow_token=arr, return_type=t, colon_token=cln, body=b, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (n := self._accept(TokenType.NAME))
            and
            (lp := self._accept('('))
            and
            (p := self._params(),)
            and
            (rp := self._accept(')'))
            and
            (cln := self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return FunctionDeclaration(name_token=n, lparen_token=lp, params=p or [], rparen_token=rp, arrow_token=None, return_type=None, colon_token=cln, body=b, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _params(self) -> list [Parameter] | None:
        # params: ','.param_no_default+ [',' ','.param_default+] ','? | ','.param_default+ ','?
        mark = self._mark()
        if (
            (a := self._gather_2())
            and
            (b := self._tmp_4(),)
            and
            (self._accept(','),)
        ):
            return a + (b or [])
        self._reset(mark)
        if (
            (a := self._gather_5())
            and
            (self._accept(','),)
        ):
            return a
        self._reset(mark)
        return None

    @memoize
    def _param_no_default(self) -> Parameter | None:
        # param_no_default: NAME ':' type !'='
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (n := self._accept(TokenType.NAME))
            and
            (cln := self._accept(':'))
            and
            (t := self._type())
            and
            (self._negative_lookahead(self._accept, '='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Parameter(name_token=n, colon_token=cln, type=t, equal_token=None, default=None, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _param_default(self) -> Parameter | None:
        # param_default: NAME ':' type '=' expression
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (n := self._accept(TokenType.NAME))
            and
            (cln := self._accept(':'))
            and
            (t := self._type())
            and
            (eq := self._accept('='))
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Parameter(name_token=n, colon_token=cln, type=t, equal_token=eq, default=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _comment(self) -> Comment | None:
        # comment: COMMENT NEWLINE
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (c := self._accept(TokenType.COMMENT))
            and
            (self._accept(TokenType.NEWLINE))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Comment(token=c, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _statement(self) -> Statement | Comment | None:
        # statement: inline_stmts | comment | compound_stmt
        mark = self._mark()
        if (
            (inline_stmts := self._inline_stmts())
        ):
            return inline_stmts
        self._reset(mark)
        if (
            (comment := self._comment())
        ):
            return comment
        self._reset(mark)
        if (
            (compound_stmt := self._compound_stmt())
        ):
            return compound_stmt
        self._reset(mark)
        return None

    @memoize
    def _block(self) -> Statement | None:
        # block: NEWLINE INDENT statement+ DEDENT | inline_stmts
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (self._accept(TokenType.NEWLINE))
            and
            (self._accept(TokenType.INDENT))
            and
            (a := self._loop1_7())
            and
            (self._accept(TokenType.DEDENT))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Block(body=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (inline_stmts := self._inline_stmts())
        ):
            return inline_stmts
        self._reset(mark)
        return None

    @memoize
    def _inline_stmts(self) -> Statement | None:
        # inline_stmts: simple_stmt !';' (NEWLINE | COMMENT_SEP) | ';'.simple_stmt+ ';'? (NEWLINE | COMMENT_SEP)
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (s := self._simple_stmt())
            and
            (self._negative_lookahead(self._accept, ';'))
            and
            (self._tmp_8())
        ):
            return s
        self._reset(mark)
        if (
            (ss := self._gather_9())
            and
            (self._accept(';'),)
            and
            (self._tmp_11())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Block(body=ss, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _simple_stmt(self) -> Statement | None:
        # simple_stmt: var_decl | assign_stmt | augassign_stmt | 'return' expression? | 'break' | 'continue' | 'pass' | expression
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (var_decl := self._var_decl())
        ):
            return var_decl
        self._reset(mark)
        if (
            (assign_stmt := self._assign_stmt())
        ):
            return assign_stmt
        self._reset(mark)
        if (
            (augassign_stmt := self._augassign_stmt())
        ):
            return augassign_stmt
        self._reset(mark)
        if (
            (kw := self._accept('return'))
            and
            (v := self._expression(),)
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ReturnStatement(return_token=kw, value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (kw := self._accept('break'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return BreakStatement(break_token=kw, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (kw := self._accept('continue'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ContinueStatement(continue_token=kw, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (kw := self._accept('pass'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return PassStatement(pass_token=kw, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (e := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ExpressionStatement(expression=e, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _assign_stmt(self) -> AssignStatement | None:
        # assign_stmt: left_expr '=' expression
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (t := self._left_expr())
            and
            (o := self._accept('='))
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return AssignStatement(target=t, equal_token=o, value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _augassign_stmt(self) -> AugAssignStatement | None:
        # augassign_stmt: left_expr augassign_op expression
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (t := self._left_expr())
            and
            (o := self._augassign_op())
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return AugAssignStatement(target=t, op=o, value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _augassign_op(self) -> ArithmeticOp | None:
        # augassign_op: '+=' | '-=' | '*=' | '/=' | '//=' | '%='
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('+='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return AddOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('-='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return SubOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('*='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return MulOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('/='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return DivOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('//='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return FloorDivOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('%='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ModOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _compound_stmt(self) -> Statement | None:
        # compound_stmt: if_stmt | while_stmt | for_stmt
        mark = self._mark()
        if (
            (if_stmt := self._if_stmt())
        ):
            return if_stmt
        self._reset(mark)
        if (
            (while_stmt := self._while_stmt())
        ):
            return while_stmt
        self._reset(mark)
        if (
            (for_stmt := self._for_stmt())
        ):
            return for_stmt
        self._reset(mark)
        return None

    @memoize
    def _var_decl(self) -> VariableDeclarationStatement | None:
        # var_decl: NAME ':' type '=' expression | NAME ':' type
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (n := self._accept(TokenType.NAME))
            and
            (cln := self._accept(':'))
            and
            (t := self._type())
            and
            (eq := self._accept('='))
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return VariableDeclarationStatement(name_token=n, colon_token=cln, type=t, equal_token=eq, value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (n := self._accept(TokenType.NAME))
            and
            (cln := self._accept(':'))
            and
            (t := self._type())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return VariableDeclarationStatement(name_token=n, colon_token=cln, type=t, equal_token=None, value=None, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _if_stmt(self) -> IfStatement | None:
        # if_stmt: 'if' expression ':' block 'else' if_stmt | 'if' expression ':' block 'else' ':' block | 'if' expression ':' block
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (kw_if := self._accept('if'))
            and
            (t := self._expression())
            and
            (cln := self._accept(':'))
            and
            (b := self._block())
            and
            (kw_else := self._accept('else'))
            and
            (el := self._if_stmt())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return IfStatement(if_token=kw_if, test=t, colon_token=cln, body=b, else_token=kw_else, else_colon_token=None, orelse=el, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (kw_if := self._accept('if'))
            and
            (t := self._expression())
            and
            (cln_if := self._accept(':'))
            and
            (b_if := self._block())
            and
            (kw_else := self._accept('else'))
            and
            (cln_else := self._accept(':'))
            and
            (b_else := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return IfStatement(if_token=kw_if, test=t, colon_token=cln_if, body=b_if, else_token=kw_else, else_colon_token=cln_else, orelse=b_else, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (kw := self._accept('if'))
            and
            (t := self._expression())
            and
            (cln := self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return IfStatement(if_token=kw, test=t, colon_token=cln, body=b, else_token=None, else_colon_token=None, orelse=None, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _while_stmt(self) -> WhileStatement | None:
        # while_stmt: 'while' expression ':' block
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (kw := self._accept('while'))
            and
            (t := self._expression())
            and
            (cln := self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return WhileStatement(while_token=kw, test=t, colon_token=cln, body=b, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _for_stmt(self) -> ForStatement | None:
        # for_stmt: 'for' '(' simple_stmt ';' expression ';' simple_stmt ')' ':' block | 'for' simple_stmt ';' expression ';' simple_stmt ':' block
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (kw := self._accept('for'))
            and
            (lp := self._accept('('))
            and
            (i := self._simple_stmt())
            and
            (s1 := self._accept(';'))
            and
            (t := self._expression())
            and
            (s2 := self._accept(';'))
            and
            (e := self._simple_stmt())
            and
            (rp := self._accept(')'))
            and
            (cln := self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ForStatement(for_token=kw, lparen_token=lp, init_stmt=i, semicolon_token1=s1, test=t, semicolon_token2=s2, end_stmt=e, rparen_token=rp, colon_token=cln, body=b, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (kw := self._accept('for'))
            and
            (i := self._simple_stmt())
            and
            (s1 := self._accept(';'))
            and
            (t := self._expression())
            and
            (s2 := self._accept(';'))
            and
            (e := self._simple_stmt())
            and
            (cln := self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ForStatement(for_token=kw, lparen_token=None, init_stmt=i, semicolon_token1=s1, test=t, semicolon_token2=s2, end_stmt=e, rparen_token=None, colon_token=cln, body=b, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _orop(self) -> OrOp | None:
        # orop: 'or'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('or'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return OrOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _andop(self) -> AndOp | None:
        # andop: 'and'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('and'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return AndOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _notop(self) -> NotOp | None:
        # notop: 'not'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('not'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return NotOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _expression(self) -> Expression | None:
        # expression: or_expr 'if' or_expr 'else' expression | or_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (b := self._or_expr())
            and
            (kw_if := self._accept('if'))
            and
            (t := self._or_expr())
            and
            (kw_else := self._accept('else'))
            and
            (e := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return IfExpression(body=b, if_token=kw_if, test=t, else_token=kw_else, orelse=e, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (or_expr := self._or_expr())
        ):
            return or_expr
        self._reset(mark)
        return None

    @memoize
    def _or_expr(self) -> Expression | None:
        # or_expr: and_expr orop expression | and_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (l := self._and_expr())
            and
            (o := self._orop())
            and
            (r := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return BinaryExpression(left=l, op=o, right=r, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (and_expr := self._and_expr())
        ):
            return and_expr
        self._reset(mark)
        return None

    @memoize
    def _and_expr(self) -> Expression | None:
        # and_expr: not_expr andop and_expr | not_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (l := self._not_expr())
            and
            (o := self._andop())
            and
            (r := self._and_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return BinaryExpression(left=l, op=o, right=r, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (not_expr := self._not_expr())
        ):
            return not_expr
        self._reset(mark)
        return None

    @memoize
    def _not_expr(self) -> Expression | None:
        # not_expr: notop comp_expr | comp_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (o := self._notop())
            and
            (a := self._comp_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return UnaryExpression(operand=a, op=o, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (comp_expr := self._comp_expr())
        ):
            return comp_expr
        self._reset(mark)
        return None

    @memoize
    def _comp_expr(self) -> Expression | None:
        # comp_expr: sum_expr compop sum_expr | sum_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (l := self._sum_expr())
            and
            (o := self._compop())
            and
            (r := self._sum_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return BinaryExpression(left=l, op=o, right=r, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (sum_expr := self._sum_expr())
        ):
            return sum_expr
        self._reset(mark)
        return None

    @memoize
    def _compop(self) -> BinaryOp | None:
        # compop: '==' | '!=' | '<' | '<=' | '>' | '>='
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('=='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return EqOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('!='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return NotEqOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('<'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return LtOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('<='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return LtEOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('>'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return GtOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('>='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return GtEOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _addop(self) -> AddOp | None:
        # addop: '+'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('+'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return AddOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _subop(self) -> SubOp | None:
        # subop: '-'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('-'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return SubOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _mulop(self) -> MulOp | None:
        # mulop: '*'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('*'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return MulOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _divop(self) -> DivOp | None:
        # divop: '/'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('/'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return DivOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _modop(self) -> ModOp | None:
        # modop: '%'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('%'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ModOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _floordivop(self) -> FloorDivOp | None:
        # floordivop: '//'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('//'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return FloorDivOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _uop(self) -> PosOp | NegOp | None:
        # uop: '+' | '-'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('+'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return PosOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('-'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return NegOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _sum_expr(self) -> Expression | None:
        # sum_expr: term_expr (addop | subop) sum_expr | term_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (l := self._term_expr())
            and
            (o := self._tmp_12())
            and
            (r := self._sum_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return BinaryExpression(left=l, op=o, right=r, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (term_expr := self._term_expr())
        ):
            return term_expr
        self._reset(mark)
        return None

    @memoize
    def _term_expr(self) -> Expression | None:
        # term_expr: atom_expr (mulop | divop | modop | floordivop) term_expr | atom_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (l := self._atom_expr())
            and
            (o := self._tmp_13())
            and
            (r := self._term_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return BinaryExpression(left=l, op=o, right=r, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (atom_expr := self._atom_expr())
        ):
            return atom_expr
        self._reset(mark)
        return None

    @memoize_left_rec
    def _atom_expr(self) -> Expression | None:
        # atom_expr: uop atom_expr | atom_expr '(' argument_list? ')' | 'true' | 'false' | NAME | (INT | FLOAT) | STRING | '(' expression ')'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (o := self._uop())
            and
            (a := self._atom_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return UnaryExpression(operand=a, op=o, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (c := self._atom_expr())
            and
            (lp := self._accept('('))
            and
            (ag := self._argument_list(),)
            and
            (rp := self._accept(')'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return CallExpression(callee=c, lparen_token=lp, args=ag or [], rparen_token=rp, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('true'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Constant(value=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('false'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Constant(value=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept(TokenType.NAME))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Identifier(token=a, context=Load(), filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._tmp_14())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Constant(value=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept(TokenType.STRING))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Constant(value=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('('))
            and
            (a := self._expression())
            and
            (self._accept(')'))
        ):
            return a
        self._reset(mark)
        return None

    @memoize
    def _left_expr(self) -> LeftExpression | None:
        # left_expr: NAME
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept(TokenType.NAME))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return Identifier(token=a, context=Store(), filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _argument_list(self) -> list [Argument] | None:
        # argument_list: ','.pos_arg+ [',' ','.kw_arg+] ','? | ','.kw_arg+ ','?
        mark = self._mark()
        if (
            (a := self._gather_15())
            and
            (b := self._tmp_17(),)
            and
            (self._accept(','),)
        ):
            return a + (b or [])
        self._reset(mark)
        if (
            (a := self._gather_18())
            and
            (self._accept(','),)
        ):
            return a
        self._reset(mark)
        return None

    @memoize
    def _pos_arg(self) -> PositionalArgument | None:
        # pos_arg: expression !'='
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (v := self._expression())
            and
            (self._negative_lookahead(self._accept, '='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return PositionalArgument(value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _kw_arg(self) -> KeywordArgument | None:
        # kw_arg: NAME '=' !',' expression
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (n := self._accept(TokenType.NAME))
            and
            (eq := self._accept('='))
            and
            (self._negative_lookahead(self._accept, ','))
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return KeywordArgument(name_token=n, equal_token=eq, value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _type(self) -> Type | None:
        # type_: 'Int' | 'Bool' | 'Float'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('Int'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return IntType(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('Bool'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return BoolType(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('Float'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return FloatType(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _loop1_1(self) -> list[Any]:
        # loop1_1: toplevel
        mark = self._mark()
        children = []
        while (
            (toplevel := self._toplevel())
        ):
            children.append(toplevel)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _loop0_3(self) -> list[Any]:
        # loop0_3: ',' param_no_default
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._param_no_default())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_2(self) -> Any | None:
        # gather_2: param_no_default loop0_3
        mark = self._mark()
        if (
            (elem := self._param_no_default())
            is not None
            and
            (seq := self._loop0_3())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _tmp_4(self) -> Any | None:
        # tmp_4: ',' ','.param_default+
        mark = self._mark()
        if (
            (self._accept(','))
            and
            (z := self._gather_20())
        ):
            return z
        self._reset(mark)
        return None

    @memoize
    def _loop0_6(self) -> list[Any]:
        # loop0_6: ',' param_default
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._param_default())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_5(self) -> Any | None:
        # gather_5: param_default loop0_6
        mark = self._mark()
        if (
            (elem := self._param_default())
            is not None
            and
            (seq := self._loop0_6())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _loop1_7(self) -> list[Any]:
        # loop1_7: statement
        mark = self._mark()
        children = []
        while (
            (statement := self._statement())
        ):
            children.append(statement)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _tmp_8(self) -> Any | None:
        # tmp_8: NEWLINE | COMMENT_SEP
        mark = self._mark()
        if (
            (newline := self._accept(TokenType.NEWLINE))
        ):
            return newline
        self._reset(mark)
        if (
            (comment_sep := self._accept(TokenType.COMMENT_SEP))
        ):
            return comment_sep
        self._reset(mark)
        return None

    @memoize
    def _loop0_10(self) -> list[Any]:
        # loop0_10: ';' simple_stmt
        mark = self._mark()
        children = []
        while (
            (self._accept(';'))
            and
            (elem := self._simple_stmt())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_9(self) -> Any | None:
        # gather_9: simple_stmt loop0_10
        mark = self._mark()
        if (
            (elem := self._simple_stmt())
            is not None
            and
            (seq := self._loop0_10())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _tmp_11(self) -> Any | None:
        # tmp_11: NEWLINE | COMMENT_SEP
        mark = self._mark()
        if (
            (newline := self._accept(TokenType.NEWLINE))
        ):
            return newline
        self._reset(mark)
        if (
            (comment_sep := self._accept(TokenType.COMMENT_SEP))
        ):
            return comment_sep
        self._reset(mark)
        return None

    @memoize
    def _tmp_12(self) -> Any | None:
        # tmp_12: addop | subop
        mark = self._mark()
        if (
            (addop := self._addop())
        ):
            return addop
        self._reset(mark)
        if (
            (subop := self._subop())
        ):
            return subop
        self._reset(mark)
        return None

    @memoize
    def _tmp_13(self) -> Any | None:
        # tmp_13: mulop | divop | modop | floordivop
        mark = self._mark()
        if (
            (mulop := self._mulop())
        ):
            return mulop
        self._reset(mark)
        if (
            (divop := self._divop())
        ):
            return divop
        self._reset(mark)
        if (
            (modop := self._modop())
        ):
            return modop
        self._reset(mark)
        if (
            (floordivop := self._floordivop())
        ):
            return floordivop
        self._reset(mark)
        return None

    @memoize
    def _tmp_14(self) -> Any | None:
        # tmp_14: INT | FLOAT
        mark = self._mark()
        if (
            (int := self._accept(TokenType.INT))
        ):
            return int
        self._reset(mark)
        if (
            (float := self._accept(TokenType.FLOAT))
        ):
            return float
        self._reset(mark)
        return None

    @memoize
    def _loop0_16(self) -> list[Any]:
        # loop0_16: ',' pos_arg
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._pos_arg())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_15(self) -> Any | None:
        # gather_15: pos_arg loop0_16
        mark = self._mark()
        if (
            (elem := self._pos_arg())
            is not None
            and
            (seq := self._loop0_16())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _tmp_17(self) -> Any | None:
        # tmp_17: ',' ','.kw_arg+
        mark = self._mark()
        if (
            (self._accept(','))
            and
            (z := self._gather_22())
        ):
            return z
        self._reset(mark)
        return None

    @memoize
    def _loop0_19(self) -> list[Any]:
        # loop0_19: ',' kw_arg
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._kw_arg())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_18(self) -> Any | None:
        # gather_18: kw_arg loop0_19
        mark = self._mark()
        if (
            (elem := self._kw_arg())
            is not None
            and
            (seq := self._loop0_19())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _loop0_21(self) -> list[Any]:
        # loop0_21: ',' param_default
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._param_default())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_20(self) -> Any | None:
        # gather_20: param_default loop0_21
        mark = self._mark()
        if (
            (elem := self._param_default())
            is not None
            and
            (seq := self._loop0_21())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _loop0_23(self) -> list[Any]:
        # loop0_23: ',' kw_arg
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._kw_arg())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_22(self) -> Any | None:
        # gather_22: kw_arg loop0_23
        mark = self._mark()
        if (
            (elem := self._kw_arg())
            is not None
            and
            (seq := self._loop0_23())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    KEYWORDS = ('Bool', 'Float', 'Int', 'and', 'break', 'continue', 'else', 'false', 'for', 'if', 'not', 'or', 'pass', 'return', 'true', 'while')
    SOFT_KEYWORDS = ()


def main():
    import argparse
    import time
    import sys
    
    argparser = argparse.ArgumentParser()
    argparser.add_argument(dest="filename", nargs="?", metavar="filename.vcs")
    argparser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print timing stats; repeat for more debug output",
    )
    argparser.add_argument(
        "-s",
        "--skip-comments",
        action="store_true",
        help="Skip all the comment tokens",
    )
    argparser.add_argument(
        "-t",
        "--tabsize",
        metavar="TABSIZE",
        default=4,
        help="How many spaces per tab character",
    )
    args = argparser.parse_args()

    filename = args.filename
    skip_comments = args.skip_comments
    verbose = args.verbose

    def cli(filename: str, source: str):
        t0 = time.time()

        errors = ErrorCollector()
        lexer = Lexer(source, filename, errors, args.tabsize)
        parser = Parser(lexer, errors, skip_comments, verbose)
        tree = parser.parse()
    
        t1 = time.time()

        if tree is None:
            last_tok = parser.diagnose()
            parser.report(ParseError(parser.get_error_info_on(last_tok)))

        if not errors.ok():
            for issue in errors.issues:
                print(dump_error(issue), file=sys.stderr)
            return
        
        if tree is None:
            return

        print(tree)
        
        if verbose:
            dt = t1 - t0
            last_tok = parser.diagnose()
            nlines = last_tok.get_endpos()[0]
            print(f"Total time: {dt:.3f} sec; {nlines} lines", end="")
            if dt:
                print(f"; {nlines / dt:.0f} lines/sec")
            else:
                print()
            print("Caches sizes:")
            print(f"  token array : {len(parser._tokenstream._tokens):10}")
            print(f"        cache : {len(parser._cache):10}")
    
    if not filename:
        from .repl import REPL
        REPL(cli).cmdloop("vcs.parser REPL (Read-Eval-Print Loop) module, type Ctrl+C to exit the program")
        exit(0)

    with open(filename, encoding="utf8") as f:
        cli(filename, f.read())



if __name__ == "__main__":
    main()
