# Auto-generated by vcs/pegen.py from vcs/vcs.gram
# To regenerate this, `cd` to the top directory of this project and run:
# `$python -m vcs.pegen vcs/vcs.gram -o vcs/parser.py`

from functools import wraps
from typing import Any, Callable, ClassVar, cast

from vcs import ast
from vcs import errors as err
from vcs import lexer as lex
from vcs import utils


type Mark = int

def _get_indent_closure() -> Callable[[int], str]:
    _INDENT_CACHE = {}

    def get_indent(level: int) -> str:
        if level not in _INDENT_CACHE:
            _INDENT_CACHE[level] = "  " * level
        return _INDENT_CACHE[level]

    return get_indent

_get_indent = _get_indent_closure()
del _get_indent_closure


def logger[F: Callable[..., Any], P: Parser](method: F) -> F:
    """
    Logging decorator for non-memoized parser methods.
    """
    method_name = method.__name__

    @wraps(method)
    def logger_wrapper(self: P, *args: object) -> Any:
        if not self.verbose:
            return method(self, *args)

        level = self._level
        fill = _get_indent(level)

        args_repr = ",".join(repr(arg) for arg in args)
        peek_repr = repr(self._showpeek())

        utils.print_info(f"{fill}{method_name}({args_repr}) .... (looking at {peek_repr})")

        self._level = level + 1
        try:
            tree = method(self, *args)
        finally:
            self._level = level

        tree_repr = repr(tree)[:80]
        utils.print_info(f"{fill}... {method_name}({args_repr}) --> {tree_repr}")
        return tree

    return cast(F, logger_wrapper)


def memoize[F: Callable[..., Any], P: Parser](method: F) -> F:
    """
    Memoization decorator for parser methods.
    """
    method_name = method.__name__

    @wraps(method)
    def memoize_wrapper(self: P, *args: object) -> Any:
        cache = self._cache
        mark = self._mark()
        key = (mark, method_name, args)

        # fast path
        if not self.verbose:
            try:
                tree, endmark = cache[key]
                self._reset(endmark)
                return tree
            except KeyError:
                pass  # continue with slow path
        else:
            # debug path
            cached = cache.get(key)
            if cached is not None:
                tree, endmark = cached
                self._reset(endmark)
                fill = _get_indent(self._level)
                args_repr = ",".join(repr(arg) for arg in args)
                tree_repr = repr(tree)[:80]
                utils.print_info(f"{fill}{method_name}({args_repr}) -> {tree_repr}")
                return tree

        # slow path
        level = self._level

        if self.verbose:
            fill = _get_indent(level)
            args_repr = ",".join(repr(arg) for arg in args)
            peek_repr = repr(self._showpeek())
            utils.print_info(f"{fill}{method_name}({args_repr}) ... (looking at {peek_repr})")

        self._level = level + 1
        try:
            tree = method(self, *args)
        finally:
            self._level = level

        endmark = self._mark()
        cache[key] = (tree, endmark)

        if self.verbose:
            tree_repr = repr(tree)[:80]
            utils.print_info(f"{fill}... {method_name}({args_repr}) -> {tree_repr}")  # type: ignore

        return tree

    return cast(F, memoize_wrapper)


def memoize_left_rec[P: Parser, T](
    method: Callable[[P], T | None],
) -> Callable[[P], T | None]:
    """
    Memoization for left-recursive grammar rules.
    """
    method_name = method.__name__

    @wraps(method)
    def memoize_left_rec_wrapper(self: P) -> T | None:
        cache = self._cache
        mark = self._mark()
        key = (mark, method_name, ())

        # fast path
        if not self.verbose:
            try:
                tree, endmark = cache[key]
                if tree is not None:
                    self._reset(endmark)
                return tree
            except KeyError:
                pass
        else:
            cached = cache.get(key)
            if cached is not None:
                tree, endmark = cached
                if tree is not None:
                    self._reset(endmark)
                fill = _get_indent(self._level)
                tree_repr = repr(tree)[:80] if tree else "None"
                utils.print_info(f"{fill}{method_name}() -> {tree_repr} [fresh]")
                return tree

        # For left-recursive rules we manipulate the cache and
        # loop until the rule shows no progress, then pick the
        # previous result. For an explanation why this works, see
        # https://github.com/PhilippeSigaud/Pegged/wiki/Left-Recursion
        # (But we use the memoization cache instead of a static
        # variable; perhaps this is similar to a paper by Warth et al
        # (http://web.cs.ucla.edu/~todd/research/pub.php?id=pepm08)

        level = self._level
        fill = _get_indent(level) if self.verbose else ""

        if self.verbose:
            peek_repr = repr(self._showpeek())
            utils.print_info(f"{fill}{method_name} ... (looking at {peek_repr})")
            utils.print_info(f"{fill}Recursive {method_name} at {mark} depth 0")

        cache[key] = (None, mark)
        lastresult: T | None = None
        lastmark = mark
        depth = 0

        self._level = level + 1
        try:
            while True:
                self._reset(mark)
                self._in_recursive_rule += 1
                try:
                    result = method(self)
                finally:
                    self._in_recursive_rule -= 1

                endmark = self._mark()
                depth += 1

                if self.verbose:
                    result_repr = repr(result)[:80] if result else "None"
                    utils.print_info(
                        f"{fill}Recursive {method_name} at {mark} depth {depth}: {result_repr} to {endmark}"
                    )

                if not result:
                    if self.verbose:
                        last_repr = repr(lastresult)[:80] if lastresult else "None"
                        utils.print_info(f"{fill}Fail with {last_repr} to {lastmark}")
                    break

                if endmark <= lastmark:
                    if self.verbose:
                        last_repr = repr(lastresult)[:80] if lastresult else "None"
                        utils.print_info(f"{fill}Bailing with {last_repr} to {lastmark}")
                    break

                cache[key] = (result, endmark)
                lastresult, lastmark = result, endmark
        finally:
            self._level = level

        self._reset(lastmark)
        tree = lastresult

        if self.verbose:
            tree_repr = repr(tree)[:80] if tree else "None"
            utils.print_info(f"{fill}{method_name}() -> {tree_repr} [cached]")

        if tree is not None:
            endmark = self._mark()
        else:
            endmark = mark
            self._reset(endmark)

        cache[key] = (tree, endmark)
        return tree

    return memoize_left_rec_wrapper


class TokenStream:
    """
    A small lookahead/rewind wrapper around a Lexer iterator.
    Keeps tokens in a buffer so callers can peek, getnext, mark/reset etc.
    """

    def __init__(self, lexer: lex.Lexer):
        self.filename = lexer.filename
        self.source = lexer.source
        self.source_lines = lexer.source_lines
        self.report = lexer.report

        self._lexer = lexer
        self._tokgen = iter(lexer)
        self._tokens: list[lex.TokenInfo] = []
        self._index: int = 0

    def get_error_info_on(self, token: lex.TokenInfo | None):
        if token is None:
            token = self._tokens[self._index - 1]
        return self._lexer.get_error_info(len(token.value), token.lexpos)

    def get_error_info_range(self, start_tok: lex.TokenInfo, end_tok: lex.TokenInfo):
        return self._lexer.get_error_info(
            end_tok.lexpos + len(end_tok.value) - start_tok.lexpos,
            start_tok.lexpos,
        )

    def getnext(self) -> lex.TokenInfo:
        tok = self.peek()
        self._index += 1
        return tok

    def peek(self) -> lex.TokenInfo:
        while self._index == len(self._tokens):
            tok = next(self._tokgen)
            self._tokens.append(tok)
        return self._tokens[self._index]

    def diagnose(self) -> lex.TokenInfo:
        if not self._tokens:
            self.getnext()
        return self._tokens[-1]

    def last_nonblank_token(self) -> lex.TokenInfo:
        for tok in reversed(self._tokens[:self._index]):
            if tok.type not in [
                lex.TokenType.ENDMARKER,
                lex.TokenType.NEWLINE,
                lex.TokenType.INDENT,
                lex.TokenType.DEDENT,
                lex.TokenType.ERRORTOKEN,
            ]:
                break
        return tok  # type: ignore

    def mark(self) -> Mark:
        return self._index

    def reset(self, index: Mark) -> None:
        if index == self._index:
            return
        assert 0 <= index <= len(self._tokens), (index, len(self._tokens))
        self._index = index


class Parser:
    """
    The main parser class.
    """

    KEYWORDS: ClassVar[tuple[str, ...]]
    SOFT_KEYWORDS: ClassVar[tuple[str, ...]]

    def __init__(self, lexer: lex.Lexer, errors: err.ErrorCollector, skip_comments=False, verbose=False):
        tokenstream = TokenStream(lexer)
        self._tokenstream = tokenstream

        self.filename = tokenstream.filename
        self.diagnose = tokenstream.diagnose
        self.errors = errors
        self.skip_comments = skip_comments
        self.verbose = verbose

        self._mark = tokenstream.mark
        self._reset = tokenstream.reset
        self._peek = tokenstream.peek
        self._getnext = tokenstream.getnext
        self._last_nonblank_token = tokenstream.last_nonblank_token
        self._source = tokenstream.source
        self._source_lines = tokenstream.source_lines

        self._call_invalid_rules = True
        self._level = 0
        self._cache: dict[tuple[Mark, str, tuple[Any, ...]], tuple[Any, Mark]] = {}
        self._in_recursive_rule = 0

    def _showpeek(self) -> str:
        # Brief token display
        token = self._peek()
        return f"{token.lineno}.{token.column}: {token.type}:{
            token.value if len(token.value) <= 64 else token.value[:64] + '...'
        }"

    @memoize
    def _accept(self, token_type: lex.TokenType | str) -> lex.TokenInfo | None:
        # Accept a token of the given type or value; returns the lex.TokenInfo or None
        while True:
            mark = self._mark()
            try:
                tok = self._getnext()
            except StopIteration:
                return None

            if not (self.skip_comments and tok.type == lex.TokenType.COMMENT):
                break
            
        if tok.type == token_type:
            if token_type == lex.TokenType.NAME and tok.value in self.KEYWORDS:
                return None
            return tok    
        if tok.type == lex.TokenType.NAME and tok.value == token_type:
            return tok
        if tok.type == lex.TokenType.OP and tok.value == token_type:
            return tok
        if (
            tok.type == lex.TokenType.NAME
            and token_type == "SOFT_KEYWORD"
            and tok.value in self.SOFT_KEYWORDS
        ):
            return tok
        
        self._reset(mark)

    def _expect(self, res: Any, expectation: lex.TokenType | str) -> lex.TokenInfo | None:
        # Ensure that a previous _accept returned a result, otherwise report an error
        if res is None:
            string = expectation.name.lower() if isinstance(expectation, lex.TokenType) else expectation
            self.report(err.ExpectationFailed(self.get_error_info_on(), string))
        return res

    def _positive_lookahead[T](self, func: Callable[..., T], *args: object) -> T:
        # Run func in lookahead mode: succeed/fail but do not consume tokens
        mark = self._mark()
        ok = func(*args)
        self._reset(mark)
        return ok

    def _negative_lookahead(self, func: Callable[..., object], *args: object) -> bool:
        # Run func in negative lookahead mode: succeed only if func would fail
        mark = self._mark()
        ok = func(*args)
        self._reset(mark)
        return not ok

    def report(self, error: err.CompilerError):
        self.errors.add(error)

    def get_error_info_on(self, node: ast.ASTNode | lex.TokenInfo | None = None) -> err.ErrorInfo:
        if isinstance(node, lex.TokenInfo) or node is None:
            return self._tokenstream.get_error_info_on(node)
        
        return err.ErrorInfo(
            node.filename,
            node.lineno,
            node.column,
            self._source,
            node.end_lineno,
            node.end_column,
        )

    def get_error_info_between(
        self,
        start_node: ast.ASTNode | lex.TokenInfo,
        end_node: ast.ASTNode | lex.TokenInfo,
    ) -> err.ErrorInfo:
        """
        Report an error where the start and end locations are known.
        """
        start_lineno, start_column = start_node.lineno, start_node.column
        end_lineno, end_column = end_node.end_lineno, end_node.end_column
        return err.ErrorInfo(start_node.filename, start_lineno, start_column, self._source, end_lineno, end_column)

    def get_error_info_starting_from(self, node: ast.ASTNode | lex.TokenInfo) -> err.ErrorInfo:
        return self.get_error_info_between(node, self._tokenstream.diagnose())

    def get_error_info_next_token(self) -> err.ErrorInfo:
        return self.get_error_info_on(self._peek())
    
    def parse(self):
        return self._start() or [ast.Module(body=[]), self.report(err.ParseError(self.get_error_info_on(self.diagnose())))][0]

    @memoize
    def _start(self) -> ast . Module | None:
        # start: module $
        mark = self._mark()
        if (
            (m := self._module())
            and
            (self._accept(lex.TokenType.ENDMARKER))
        ):
            return m
        self._reset(mark)
        return None

    @memoize
    def _module(self) -> ast . Module | None:
        # module: toplevel+
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (f := self._loop1_1())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Module(body=f, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _toplevel(self) -> ast . FunctionDeclaration | ast . Comment | None:
        # toplevel: func_decl | comment
        mark = self._mark()
        if (
            (func_decl := self._func_decl())
        ):
            return func_decl
        self._reset(mark)
        if (
            (comment := self._comment())
        ):
            return comment
        self._reset(mark)
        return None

    @memoize
    def _func_decl(self) -> ast . FunctionDeclaration | None:
        # func_decl: NAME '(' params? ')' '->' type ':' block | NAME '(' params? ')' ':' block
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (n := self._accept(lex.TokenType.NAME))
            and
            (self._accept('('))
            and
            (p := self._params(),)
            and
            (self._accept(')'))
            and
            (self._accept('->'))
            and
            (t := self._type())
            and
            (self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.FunctionDeclaration(name=n.value, params=p or [], return_type=t, body=b, name_token=n, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (n := self._accept(lex.TokenType.NAME))
            and
            (self._accept('('))
            and
            (p := self._params(),)
            and
            (self._accept(')'))
            and
            (self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.FunctionDeclaration(name=n.value, params=p or [], return_type=None, body=b, name_token=n, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _params(self) -> list [ast . Parameter] | None:
        # params: ','.param_no_default+ [',' ','.param_default+] ','? | ','.param_default+ ','?
        mark = self._mark()
        if (
            (a := self._gather_2())
            and
            (b := self._tmp_4(),)
            and
            (self._accept(','),)
        ):
            return a + (b or [])
        self._reset(mark)
        if (
            (a := self._gather_5())
            and
            (self._accept(','),)
        ):
            return a
        self._reset(mark)
        return None

    @memoize
    def _param_no_default(self) -> ast . Parameter | None:
        # param_no_default: NAME ':' type !'='
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (n := self._accept(lex.TokenType.NAME))
            and
            (self._accept(':'))
            and
            (t := self._type())
            and
            (self._negative_lookahead(self._accept, '='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Parameter(name=n.value, type=t, default=None, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _param_default(self) -> ast . Parameter | None:
        # param_default: NAME ':' type '=' expression
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (n := self._accept(lex.TokenType.NAME))
            and
            (self._accept(':'))
            and
            (t := self._type())
            and
            (self._accept('='))
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Parameter(name=n.value, type=t, default=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _comment(self) -> ast . Comment | None:
        # comment: COMMENT NEWLINE
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (c := self._accept(lex.TokenType.COMMENT))
            and
            (self._accept(lex.TokenType.NEWLINE))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Comment(value=c.value, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _statement(self) -> ast . Statement | ast . Comment | None:
        # statement: inline_stmts | comment | compound_stmt
        mark = self._mark()
        if (
            (inline_stmts := self._inline_stmts())
        ):
            return inline_stmts
        self._reset(mark)
        if (
            (comment := self._comment())
        ):
            return comment
        self._reset(mark)
        if (
            (compound_stmt := self._compound_stmt())
        ):
            return compound_stmt
        self._reset(mark)
        return None

    @memoize
    def _block(self) -> ast . Statement | None:
        # block: NEWLINE INDENT statement+ DEDENT | inline_stmts
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (self._accept(lex.TokenType.NEWLINE))
            and
            (self._accept(lex.TokenType.INDENT))
            and
            (a := self._loop1_7())
            and
            (self._accept(lex.TokenType.DEDENT))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Block(body=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (inline_stmts := self._inline_stmts())
        ):
            return inline_stmts
        self._reset(mark)
        return None

    @memoize
    def _inline_stmts(self) -> ast . Statement | None:
        # inline_stmts: simple_stmt !';' (NEWLINE | COMMENT_SEP) | ';'.simple_stmt+ ';'? (NEWLINE | COMMENT_SEP)
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (s := self._simple_stmt())
            and
            (self._negative_lookahead(self._accept, ';'))
            and
            (self._tmp_8())
        ):
            return s
        self._reset(mark)
        if (
            (ss := self._gather_9())
            and
            (self._accept(';'),)
            and
            (self._tmp_11())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Block(body=ss, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _simple_stmt(self) -> ast . Statement | None:
        # simple_stmt: var_decl | assign_stmt | augassign_stmt | 'tell' expression | 'return' expression? | 'break' | 'continue' | 'pass' | expression
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (var_decl := self._var_decl())
        ):
            return var_decl
        self._reset(mark)
        if (
            (assign_stmt := self._assign_stmt())
        ):
            return assign_stmt
        self._reset(mark)
        if (
            (augassign_stmt := self._augassign_stmt())
        ):
            return augassign_stmt
        self._reset(mark)
        if (
            (self._accept('tell'))
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.TellStatement(value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('return'))
            and
            (v := self._expression(),)
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.ReturnStatement(value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('break'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.BreakStatement(filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('continue'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.ContinueStatement(filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('pass'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.PassStatement(filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (e := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.ExpressionStatement(expression=e, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _assign_stmt(self) -> ast . AssignStatement | None:
        # assign_stmt: left_expr '=' expression
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (t := self._left_expr())
            and
            (self._accept('='))
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.AssignStatement(target=t, value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _augassign_stmt(self) -> ast . AugAssignStatement | None:
        # augassign_stmt: left_expr augassign_op expression
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (t := self._left_expr())
            and
            (o := self._augassign_op())
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.AugAssignStatement(target=t, op=o, value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _augassign_op(self) -> ast . ArithmeticOp | None:
        # augassign_op: '+=' | '-=' | '*=' | '/=' | '//=' | '%='
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('+='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.AddOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('-='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.SubOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('*='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.MulOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('/='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.DivOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('//='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.FloorDivOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('%='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.ModOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _compound_stmt(self) -> ast . Statement | None:
        # compound_stmt: if_stmt | while_stmt | for_stmt
        mark = self._mark()
        if (
            (if_stmt := self._if_stmt())
        ):
            return if_stmt
        self._reset(mark)
        if (
            (while_stmt := self._while_stmt())
        ):
            return while_stmt
        self._reset(mark)
        if (
            (for_stmt := self._for_stmt())
        ):
            return for_stmt
        self._reset(mark)
        return None

    @memoize
    def _var_decl(self) -> ast . VariableDeclarationStatement | None:
        # var_decl: NAME ':' type '=' expression | NAME ':' type
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (n := self._accept(lex.TokenType.NAME))
            and
            (self._accept(':'))
            and
            (t := self._type())
            and
            (self._accept('='))
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.VariableDeclarationStatement(name=n.value, type=t, value=v, name_token=n, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (n := self._accept(lex.TokenType.NAME))
            and
            (self._accept(':'))
            and
            (t := self._type())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.VariableDeclarationStatement(name=n.value, type=t, value=None, name_token=n, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _if_stmt(self) -> ast . IfStatement | None:
        # if_stmt: 'if' expression ':' block 'else' if_stmt | 'if' expression ':' block 'else' ':' block | 'if' expression ':' block
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (self._accept('if'))
            and
            (t := self._expression())
            and
            (self._accept(':'))
            and
            (b := self._block())
            and
            (self._accept('else'))
            and
            (el := self._if_stmt())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.IfStatement(test=t, body=b, orelse=el, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('if'))
            and
            (t := self._expression())
            and
            (self._accept(':'))
            and
            (b_if := self._block())
            and
            (self._accept('else'))
            and
            (self._accept(':'))
            and
            (b_else := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.IfStatement(test=t, body=b_if, orelse=b_else, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('if'))
            and
            (t := self._expression())
            and
            (self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.IfStatement(test=t, body=b, orelse=None, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _while_stmt(self) -> ast . WhileStatement | None:
        # while_stmt: 'while' expression ':' block | 'while' ':' block
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (self._accept('while'))
            and
            (t := self._expression())
            and
            (self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.WhileStatement(test=t, body=b, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('while'))
            and
            (self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.WhileStatement(test=None, body=b, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _for_stmt(self) -> ast . ForStatement | None:
        # for_stmt: 'for' '(' simple_stmt? ';' expression? ';' simple_stmt? ')' ':' block | 'for' simple_stmt? ';' expression? ';' simple_stmt? ':' block
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (self._accept('for'))
            and
            (self._accept('('))
            and
            (i := self._simple_stmt(),)
            and
            (self._accept(';'))
            and
            (t := self._expression(),)
            and
            (self._accept(';'))
            and
            (e := self._simple_stmt(),)
            and
            (self._accept(')'))
            and
            (self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.ForStatement(init_stmt=i, test=t, end_stmt=e, body=b, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('for'))
            and
            (i := self._simple_stmt(),)
            and
            (self._accept(';'))
            and
            (t := self._expression(),)
            and
            (self._accept(';'))
            and
            (e := self._simple_stmt(),)
            and
            (self._accept(':'))
            and
            (b := self._block())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.ForStatement(init_stmt=i, test=t, end_stmt=e, body=b, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _orop(self) -> ast . OrOp | None:
        # orop: 'or'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('or'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.OrOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _andop(self) -> ast . AndOp | None:
        # andop: 'and'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('and'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.AndOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _notop(self) -> ast . NotOp | None:
        # notop: 'not'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('not'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.NotOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _expression(self) -> ast . Expression | None:
        # expression: or_expr 'if' or_expr 'else' expression | or_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (b := self._or_expr())
            and
            (self._accept('if'))
            and
            (t := self._or_expr())
            and
            (self._accept('else'))
            and
            (e := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.IfExpression(body=b, test=t, orelse=e, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (or_expr := self._or_expr())
        ):
            return or_expr
        self._reset(mark)
        return None

    @memoize
    def _or_expr(self) -> ast . Expression | None:
        # or_expr: and_expr orop expression | and_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (l := self._and_expr())
            and
            (o := self._orop())
            and
            (r := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.BinaryExpression(lhs=l, op=o, rhs=r, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (and_expr := self._and_expr())
        ):
            return and_expr
        self._reset(mark)
        return None

    @memoize
    def _and_expr(self) -> ast . Expression | None:
        # and_expr: not_expr andop and_expr | not_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (l := self._not_expr())
            and
            (o := self._andop())
            and
            (r := self._and_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.BinaryExpression(lhs=l, op=o, rhs=r, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (not_expr := self._not_expr())
        ):
            return not_expr
        self._reset(mark)
        return None

    @memoize
    def _not_expr(self) -> ast . Expression | None:
        # not_expr: notop comp_expr | comp_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (o := self._notop())
            and
            (a := self._comp_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.UnaryExpression(operand=a, op=o, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (comp_expr := self._comp_expr())
        ):
            return comp_expr
        self._reset(mark)
        return None

    @memoize
    def _comp_expr(self) -> ast . Expression | None:
        # comp_expr: sum_expr compop sum_expr | sum_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (l := self._sum_expr())
            and
            (o := self._compop())
            and
            (r := self._sum_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.BinaryExpression(lhs=l, op=o, rhs=r, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (sum_expr := self._sum_expr())
        ):
            return sum_expr
        self._reset(mark)
        return None

    @memoize
    def _compop(self) -> ast . BinaryOp | None:
        # compop: '==' | '!=' | '<' | '<=' | '>' | '>='
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('=='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.EqOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('!='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.NeOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('<'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.LtOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('<='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.LeOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('>'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.GtOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('>='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.GeOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _addop(self) -> ast . AddOp | None:
        # addop: '+'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('+'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.AddOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _subop(self) -> ast . SubOp | None:
        # subop: '-'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('-'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.SubOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _mulop(self) -> ast . MulOp | None:
        # mulop: '*'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('*'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.MulOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _divop(self) -> ast . DivOp | None:
        # divop: '/'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('/'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.DivOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _modop(self) -> ast . ModOp | None:
        # modop: '%'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('%'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.ModOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _floordivop(self) -> ast . FloorDivOp | None:
        # floordivop: '//'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('//'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.FloorDivOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _uop(self) -> ast . PosOp | ast . NegOp | None:
        # uop: '+' | '-'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept('+'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.PosOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept('-'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.NegOp(token=a, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _sum_expr(self) -> ast . Expression | None:
        # sum_expr: term_expr (addop | subop) sum_expr | term_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (l := self._term_expr())
            and
            (o := self._tmp_12())
            and
            (r := self._sum_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.BinaryExpression(lhs=l, op=o, rhs=r, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (term_expr := self._term_expr())
        ):
            return term_expr
        self._reset(mark)
        return None

    @memoize_left_rec
    def _term_expr(self) -> ast . Expression | None:
        # term_expr: term_expr (mulop | divop | modop | floordivop) atom_expr | atom_expr
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (l := self._term_expr())
            and
            (o := self._tmp_13())
            and
            (r := self._atom_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.BinaryExpression(lhs=l, op=o, rhs=r, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (atom_expr := self._atom_expr())
        ):
            return atom_expr
        self._reset(mark)
        return None

    @memoize_left_rec
    def _atom_expr(self) -> ast . Expression | None:
        # atom_expr: uop atom_expr | atom_expr '(' argument_list? ')' | 'true' | 'false' | NAME | INT | FLOAT | FIXED | STRING | '(' expression ')'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (o := self._uop())
            and
            (a := self._atom_expr())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.UnaryExpression(operand=a, op=o, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (c := self._atom_expr())
            and
            (self._accept('('))
            and
            (ag := self._argument_list(),)
            and
            (self._accept(')'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.CallExpression(callee=c, args=ag or [], filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('true'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Constant(value=True, type=ast.BoolType(), filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('false'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Constant(value=False, type=ast.BoolType(), filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept(lex.TokenType.NAME))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Identifier(name=a.value, context=ast.Load(), filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept(lex.TokenType.INT))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Constant(value=int(a.value), type=ast.IntType(), filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept(lex.TokenType.FLOAT))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Constant(value=float(a.value[:-1]), type=ast.FloatType(), filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept(lex.TokenType.FIXED))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Constant(value=float(a.value[:-1]), type=ast.FixedType(), filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (a := self._accept(lex.TokenType.STRING))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Constant(value=a.value, type=ast.StringType(), filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('('))
            and
            (a := self._expression())
            and
            (self._accept(')'))
        ):
            return a
        self._reset(mark)
        return None

    @memoize
    def _left_expr(self) -> ast . LeftExpression | None:
        # left_expr: NAME
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (a := self._accept(lex.TokenType.NAME))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.Identifier(name=a.value, context=ast.Store(), filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _argument_list(self) -> list [ast . Argument] | None:
        # argument_list: ','.pos_arg+ [',' ','.kw_arg+] ','? | ','.kw_arg+ ','?
        mark = self._mark()
        if (
            (a := self._gather_14())
            and
            (b := self._tmp_16(),)
            and
            (self._accept(','),)
        ):
            return a + (b or [])
        self._reset(mark)
        if (
            (a := self._gather_17())
            and
            (self._accept(','),)
        ):
            return a
        self._reset(mark)
        return None

    @memoize
    def _pos_arg(self) -> ast . PositionalArgument | None:
        # pos_arg: expression !'='
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (v := self._expression())
            and
            (self._negative_lookahead(self._accept, '='))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.PositionalArgument(value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _kw_arg(self) -> ast . KeywordArgument | None:
        # kw_arg: NAME '=' !',' expression
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (n := self._accept(lex.TokenType.NAME))
            and
            (self._accept('='))
            and
            (self._negative_lookahead(self._accept, ','))
            and
            (v := self._expression())
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.KeywordArgument(name=n.value, value=v, filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _type(self) -> ast . Type | None:
        # type_: 'Int' | 'Bool' | 'Fixed' | 'Float'
        mark = self._mark()
        tok = self._peek()
        start_lineno, start_column = tok.lineno, tok.column
        if (
            (self._accept('Int'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.IntType(filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('Bool'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.BoolType(filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('Fixed'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.FixedType(filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        if (
            (self._accept('Float'))
        ):
            tok = self._last_nonblank_token()
            end_lineno, end_column = tok.end_lineno, tok.end_column
            return ast.FloatType(filename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column)
        self._reset(mark)
        return None

    @memoize
    def _loop1_1(self) -> list[Any]:
        # loop1_1: toplevel
        mark = self._mark()
        children = []
        while (
            (toplevel := self._toplevel())
        ):
            children.append(toplevel)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _loop0_3(self) -> list[Any]:
        # loop0_3: ',' param_no_default
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._param_no_default())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_2(self) -> Any | None:
        # gather_2: param_no_default loop0_3
        mark = self._mark()
        if (
            (elem := self._param_no_default())
            is not None
            and
            (seq := self._loop0_3())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _tmp_4(self) -> Any | None:
        # tmp_4: ',' ','.param_default+
        mark = self._mark()
        if (
            (self._accept(','))
            and
            (z := self._gather_19())
        ):
            return z
        self._reset(mark)
        return None

    @memoize
    def _loop0_6(self) -> list[Any]:
        # loop0_6: ',' param_default
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._param_default())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_5(self) -> Any | None:
        # gather_5: param_default loop0_6
        mark = self._mark()
        if (
            (elem := self._param_default())
            is not None
            and
            (seq := self._loop0_6())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _loop1_7(self) -> list[Any]:
        # loop1_7: statement
        mark = self._mark()
        children = []
        while (
            (statement := self._statement())
        ):
            children.append(statement)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _tmp_8(self) -> Any | None:
        # tmp_8: NEWLINE | COMMENT_SEP
        mark = self._mark()
        if (
            (newline := self._accept(lex.TokenType.NEWLINE))
        ):
            return newline
        self._reset(mark)
        if (
            (comment_sep := self._accept(lex.TokenType.COMMENT_SEP))
        ):
            return comment_sep
        self._reset(mark)
        return None

    @memoize
    def _loop0_10(self) -> list[Any]:
        # loop0_10: ';' simple_stmt
        mark = self._mark()
        children = []
        while (
            (self._accept(';'))
            and
            (elem := self._simple_stmt())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_9(self) -> Any | None:
        # gather_9: simple_stmt loop0_10
        mark = self._mark()
        if (
            (elem := self._simple_stmt())
            is not None
            and
            (seq := self._loop0_10())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _tmp_11(self) -> Any | None:
        # tmp_11: NEWLINE | COMMENT_SEP
        mark = self._mark()
        if (
            (newline := self._accept(lex.TokenType.NEWLINE))
        ):
            return newline
        self._reset(mark)
        if (
            (comment_sep := self._accept(lex.TokenType.COMMENT_SEP))
        ):
            return comment_sep
        self._reset(mark)
        return None

    @memoize
    def _tmp_12(self) -> Any | None:
        # tmp_12: addop | subop
        mark = self._mark()
        if (
            (addop := self._addop())
        ):
            return addop
        self._reset(mark)
        if (
            (subop := self._subop())
        ):
            return subop
        self._reset(mark)
        return None

    @memoize
    def _tmp_13(self) -> Any | None:
        # tmp_13: mulop | divop | modop | floordivop
        mark = self._mark()
        if (
            (mulop := self._mulop())
        ):
            return mulop
        self._reset(mark)
        if (
            (divop := self._divop())
        ):
            return divop
        self._reset(mark)
        if (
            (modop := self._modop())
        ):
            return modop
        self._reset(mark)
        if (
            (floordivop := self._floordivop())
        ):
            return floordivop
        self._reset(mark)
        return None

    @memoize
    def _loop0_15(self) -> list[Any]:
        # loop0_15: ',' pos_arg
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._pos_arg())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_14(self) -> Any | None:
        # gather_14: pos_arg loop0_15
        mark = self._mark()
        if (
            (elem := self._pos_arg())
            is not None
            and
            (seq := self._loop0_15())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _tmp_16(self) -> Any | None:
        # tmp_16: ',' ','.kw_arg+
        mark = self._mark()
        if (
            (self._accept(','))
            and
            (z := self._gather_21())
        ):
            return z
        self._reset(mark)
        return None

    @memoize
    def _loop0_18(self) -> list[Any]:
        # loop0_18: ',' kw_arg
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._kw_arg())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_17(self) -> Any | None:
        # gather_17: kw_arg loop0_18
        mark = self._mark()
        if (
            (elem := self._kw_arg())
            is not None
            and
            (seq := self._loop0_18())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _loop0_20(self) -> list[Any]:
        # loop0_20: ',' param_default
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._param_default())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_19(self) -> Any | None:
        # gather_19: param_default loop0_20
        mark = self._mark()
        if (
            (elem := self._param_default())
            is not None
            and
            (seq := self._loop0_20())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    @memoize
    def _loop0_22(self) -> list[Any]:
        # loop0_22: ',' kw_arg
        mark = self._mark()
        children = []
        while (
            (self._accept(','))
            and
            (elem := self._kw_arg())
        ):
            children.append(elem)
            mark = self._mark()
        self._reset(mark)
        return children

    @memoize
    def _gather_21(self) -> Any | None:
        # gather_21: kw_arg loop0_22
        mark = self._mark()
        if (
            (elem := self._kw_arg())
            is not None
            and
            (seq := self._loop0_22())
            is not None
        ):
            return [elem] + seq
        self._reset(mark)
        return None

    KEYWORDS = ('Bool', 'Fixed', 'Float', 'Int', 'and', 'break', 'continue', 'else', 'false', 'for', 'if', 'not', 'or', 'pass', 'return', 'tell', 'true', 'while')
    SOFT_KEYWORDS = ()


if __name__ == "__main__":
    from vcs.cli import cli
    cli()
