from __future__ import annotations

import argparse
import ast
import contextlib
import re
import time
import token
import tokenize
from abc import abstractmethod
from typing import IO, Any, Callable, Iterable, Iterator, NoReturn, cast

from functools import wraps
from typing import Any, Callable, cast

from vcs.lexer import TokenType

type Plain = Leaf | Group
type Item = Plain | Opt | Repeat | Forced | Lookahead | Rhs | Cut
type RuleName = tuple[str, str]
type MetaTuple = tuple[str, str | None]
type MetaList = list[MetaTuple]
type RuleList = list[Rule]
type NamedItemList = list[NamedItem]
type LookaheadOrCut = Lookahead | Forced | Cut

# Global flag whether we want actions in the comments -- default off
SIMPLE_STR = True

MODULE_PREFIX = """\
# Auto-generated by vcs/pegen.py from {filename}
# To regenerate this, `cd` to the top directory of this project and run:
# `$python -m vcs.pegen {filename} -o {output}`

from typing import Any, Callable, ClassVar, cast
from functools import wraps

from vcs.errors import *
from vcs.lexer import Lexer, TokenInfo, TokenType

{subheader}

type Mark = int

def _get_indent_closure() -> Callable[[int], str]:
    _INDENT_CACHE = {{}}

    def get_indent(level: int) -> str:
        if level not in _INDENT_CACHE:
            _INDENT_CACHE[level] = "  " * level
        return _INDENT_CACHE[level]

    return get_indent

_get_indent = _get_indent_closure()
del _get_indent_closure


def logger[F: Callable[..., Any], P: {class_name}](method: F) -> F:
    \"""
    logging decorator for non-memoized parser methods
    \"""
    method_name = method.__name__

    @wraps(method)
    def logger_wrapper(self: P, *args: object) -> Any:
        if not self.verbose:
            return method(self, *args)

        level = self._level
        fill = _get_indent(level)

        args_repr = ",".join(repr(arg) for arg in args)
        peek_repr = repr(self._showpeek())

        print(f"{{fill}}{{method_name}}({{args_repr}}) .... (looking at {{peek_repr}})\\n")

        self._level = level + 1
        try:
            tree = method(self, *args)
        finally:
            self._level = level

        tree_repr = repr(tree)[:80]
        print(f"{{fill}}... {{method_name}}({{args_repr}}) --> {{tree_repr}}\\n")
        return tree

    return cast(F, logger_wrapper)


def memoize[F: Callable[..., Any], P: {class_name}](method: F) -> F:
    \"""
    memoization decorator for parser methods
    \"""
    method_name = method.__name__

    @wraps(method)
    def memoize_wrapper(self: P, *args: object) -> Any:
        cache = self._cache
        mark = self._mark()
        key = (mark, method_name, args)

        # fast path
        if not self.verbose:
            try:
                tree, endmark = cache[key]
                self._reset(endmark)
                return tree
            except KeyError:
                pass  # continue with slow path
        else:
            # debug path
            cached = cache.get(key)
            if cached is not None:
                tree, endmark = cached
                self._reset(endmark)
                fill = _get_indent(self._level)
                args_repr = ",".join(repr(arg) for arg in args)
                tree_repr = repr(tree)[:80]
                print(f"{{fill}}{{method_name}}({{args_repr}}) -> {{tree_repr}}\\n")
                return tree

        # slow path
        level = self._level

        if self.verbose:
            fill = _get_indent(level)
            args_repr = ",".join(repr(arg) for arg in args)
            peek_repr = repr(self._showpeek())
            print(f"{{fill}}{{method_name}}({{args_repr}}) ... (looking at {{peek_repr}})\\n")

        self._level = level + 1
        try:
            tree = method(self, *args)
        finally:
            self._level = level

        endmark = self._mark()
        cache[key] = (tree, endmark)

        if self.verbose:
            tree_repr = repr(tree)[:80]
            print(f"{{fill}}... {{method_name}}({{args_repr}}) -> {{tree_repr}}\\n")  # type: ignore

        return tree

    return cast(F, memoize_wrapper)


def memoize_left_rec[P: {class_name}, T](
    method: Callable[[P], T | None],
) -> Callable[[P], T | None]:
    \"""
    memoization for left-recursive grammar rules
    \"""
    method_name = method.__name__

    @wraps(method)
    def memoize_left_rec_wrapper(self: P) -> T | None:
        cache = self._cache
        mark = self._mark()
        key = (mark, method_name, ())

        # fast path
        if not self.verbose:
            try:
                tree, endmark = cache[key]
                if tree is not None:
                    self._reset(endmark)
                return tree
            except KeyError:
                pass
        else:
            cached = cache.get(key)
            if cached is not None:
                tree, endmark = cached
                if tree is not None:
                    self._reset(endmark)
                fill = _get_indent(self._level)
                tree_repr = repr(tree)[:80] if tree else "None"
                print(f"{{fill}}{{method_name}}() -> {{tree_repr}} [fresh]\\n")
                return tree

        # For left-recursive rules we manipulate the cache and
        # loop until the rule shows no progress, then pick the
        # previous result. For an explanation why this works, see
        # https://github.com/PhilippeSigaud/Pegged/wiki/Left-Recursion
        # (But we use the memoization cache instead of a static
        # variable; perhaps this is similar to a paper by Warth et al
        # (http://web.cs.ucla.edu/~todd/research/pub.php?id=pepm08)

        level = self._level
        fill = _get_indent(level) if self.verbose else ""

        if self.verbose:
            peek_repr = repr(self._showpeek())
            print(f"{{fill}}{{method_name}} ... (looking at {{peek_repr}})\\n")
            print(f"{{fill}}Recursive {{method_name}} at {{mark}} depth 0\\n")

        cache[key] = (None, mark)
        lastresult: T | None = None
        lastmark = mark
        depth = 0

        self._level = level + 1
        try:
            while True:
                self._reset(mark)
                self._in_recursive_rule += 1
                try:
                    result = method(self)
                finally:
                    self._in_recursive_rule -= 1

                endmark = self._mark()
                depth += 1

                if self.verbose:
                    result_repr = repr(result)[:80] if result else "None"
                    print(
                        f"{{fill}}Recursive {{method_name}} at {{mark}} depth {{depth}}: "
                        f"{{result_repr}} to {{endmark}}\\n"
                    )

                if not result:
                    if self.verbose:
                        last_repr = repr(lastresult)[:80] if lastresult else "None"
                        print(f"{{fill}}Fail with {{last_repr}} to {{lastmark}}\\n")
                    break

                if endmark <= lastmark:
                    if self.verbose:
                        last_repr = repr(lastresult)[:80] if lastresult else "None"
                        print(f"{{fill}}Bailing with {{last_repr}} to {{lastmark}}\\n")
                    break

                cache[key] = (result, endmark)
                lastresult, lastmark = result, endmark
        finally:
            self._level = level

        self._reset(lastmark)
        tree = lastresult

        if self.verbose:
            tree_repr = repr(tree)[:80] if tree else "None"
            print(f"{{fill}}{{method_name}}() -> {{tree_repr}} [cached]\\n")

        if tree is not None:
            endmark = self._mark()
        else:
            endmark = mark
            self._reset(endmark)

        cache[key] = (tree, endmark)
        return tree

    return memoize_left_rec_wrapper


class TokenStream:
    \"""
    A small lookahead/rewind wrapper around a Lexer iterator
    Keeps tokens in a buffer so callers can peek, getnext, mark/reset etc
    \"""

    def __init__(self, lexer: Lexer):
        self.filename = lexer.filename
        self.source = lexer.source
        self.source_lines = lexer.source_lines
        self.report = lexer.report

        self._lexer = lexer
        self._tokgen = iter(lexer)
        self._tokens: list[TokenInfo] = []
        self._index: int = 0

    def get_error_info_on(self, token: TokenInfo | None):
        if token is None:
            token = self._tokens[self._index - 1]
        return self._lexer.get_error_info(len(token.value), token.lexpos)

    def get_error_info_range(self, start_tok: TokenInfo, end_tok: TokenInfo):
        return self._lexer.get_error_info(
            end_tok.lexpos + len(end_tok.value) - start_tok.lexpos,
            start_tok.lexpos,
        )

    def getnext(self) -> TokenInfo:
        tok = self.peek()
        self._index += 1
        return tok

    def peek(self) -> TokenInfo:
        while self._index == len(self._tokens):
            tok = next(self._tokgen)
            self._tokens.append(tok)
        return self._tokens[self._index]

    def diagnose(self) -> TokenInfo:
        if not self._tokens:
            self.getnext()
        return self._tokens[-1]

    def last_nonblank_token(self) -> TokenInfo:
        for tok in reversed(self._tokens[:self._index]):
            if tok.type not in [
                TokenType.ENDMARKER,
                TokenType.NEWLINE,
                TokenType.INDENT,
                TokenType.DEDENT,
                TokenType.ERRORTOKEN,
            ]:
                break
        return tok  # type: ignore

    def mark(self) -> Mark:
        return self._index

    def reset(self, index: Mark) -> None:
        if index == self._index:
            return
        assert 0 <= index <= len(self._tokens), (index, len(self._tokens))
        self._index = index


class {class_name}:
    \"""
    The main parser class
    \"""

    KEYWORDS: ClassVar[tuple[str, ...]]
    SOFT_KEYWORDS: ClassVar[tuple[str, ...]]

    def __init__(self, lexer: Lexer, errors: ErrorCollector, skip_comments=False, verbose=False):
        tokenstream = TokenStream(lexer)
        self._tokenstream = tokenstream

        self.filename = tokenstream.filename
        self.diagnose = tokenstream.diagnose
        self.errors = errors
        self.skip_comments = skip_comments
        self.verbose = verbose

        self._mark = tokenstream.mark
        self._reset = tokenstream.reset
        self._peek = tokenstream.peek
        self._getnext = tokenstream.getnext
        self._last_nonblank_token = tokenstream.last_nonblank_token
        self._source = tokenstream.source
        self._source_lines = tokenstream.source_lines

        self._call_invalid_rules = True
        self._level = 0
        self._cache: dict[tuple[Mark, str, tuple[Any, ...]], tuple[Any, Mark]] = {{}}
        self._in_recursive_rule = 0

    def _showpeek(self) -> str:
        # Brief token display
        token = self._peek()
        return f"{{token.lineno}}.{{token.column}}: {{token.type}}:{{
            token.value if len(token.value) <= 64 else token.value[:64] + '...'
        }}"

    @memoize
    def _accept(self, token_type: TokenType | str) -> TokenInfo | None:
        # Accept a token of the given type or value; returns the TokenInfo or None
        while True:
            mark = self._mark()
            try:
                tok = self._getnext()
            except StopIteration:
                return None

            if not (self.skip_comments and tok.type == TokenType.COMMENT):
                break
            
        if tok.type == token_type:
            if token_type == TokenType.NAME and tok.value in self.KEYWORDS:
                return None
            return tok    
        if tok.type == TokenType.NAME and tok.value == token_type:
            return tok
        if tok.type == TokenType.OP and tok.value == token_type:
            return tok
        if (
            tok.type == TokenType.NAME
            and token_type == "SOFT_KEYWORD"
            and tok.value in self.SOFT_KEYWORDS
        ):
            return tok
        
        self._reset(mark)

    def _expect(self, res: Any, expectation: TokenType | str) -> TokenInfo | None:
        # Ensure that a previous _accept returned a result, otherwise report an error
        if res is None:
            string = expectation.name.lower() if isinstance(expectation, TokenType) else expectation
            self.report(ExpectationFailed(self.get_error_info_on(), string))
        return res

    def _positive_lookahead[T](self, func: Callable[..., T], *args: object) -> T:
        # Run func in lookahead mode: succeed/fail but do not consume tokens
        mark = self._mark()
        ok = func(*args)
        self._reset(mark)
        return ok

    def _negative_lookahead(self, func: Callable[..., object], *args: object) -> bool:
        # Run func in negative lookahead mode: succeed only if func would fail
        mark = self._mark()
        ok = func(*args)
        self._reset(mark)
        return not ok

    def report(self, error: CompilerError):
        self.errors.add(error)

    def get_error_info_on(self, node: ASTNode | TokenInfo | None = None) -> ErrorInfo:
        if isinstance(node, TokenInfo) or node is None:
            return self._tokenstream.get_error_info_on(node)
        
        return ErrorInfo(
            node.filename,
            node.lineno,
            node.column,
            self._source,
            node.end_lineno,
            node.end_column,
        )

    def get_error_info_between(
        self,
        start_node: ASTNode | TokenInfo,
        end_node: ASTNode | TokenInfo,
    ) -> ErrorInfo:
        \"""
        Report an error where the start and end locations are known
        \"""
        start_lineno, start_column = start_node.lineno, start_node.column

        if isinstance(end_node, TokenInfo):
            end_lineno, end_column = end_node.get_endpos()
        else:
            end_lineno, end_column = end_node.end_lineno, end_node.end_column

        return ErrorInfo(start_node.filename, start_lineno, start_column, self._source, end_lineno, end_column)

    def get_error_info_starting_from(self, node: ASTNode | TokenInfo) -> ErrorInfo:
        return self.get_error_info_between(node, self._tokenstream.diagnose())

    def get_error_info_next_token(self) -> ErrorInfo:
        return self.get_error_info_on(self._peek())
    
    def parse(self):
        return self._start() or {fallback}

"""

MODULE_SUFFIX = """

def main():
    import argparse
    import time
    import sys
    
    argparser = argparse.ArgumentParser()
    argparser.add_argument(dest="filename", nargs="?", metavar="filename.vcs")
    argparser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print timing stats; repeat for more debug output",
    )
    argparser.add_argument(
        "-s",
        "--skip-comments",
        action="store_true",
        help="Skip all the comment tokens",
    )
    argparser.add_argument(
        "-t",
        "--tabsize",
        metavar="TABSIZE",
        default=4,
        help="How many spaces per tab character",
    )
    args = argparser.parse_args()

    filename = args.filename
    skip_comments = args.skip_comments
    verbose = args.verbose

    def cli(filename: str, source: str):
        t0 = time.time()

        errors = ErrorCollector()
        lexer = Lexer(source, filename, errors, args.tabsize)
        parser = Parser(lexer, errors, skip_comments, verbose)
        tree = parser.parse()
    
        t1 = time.time()

        if tree is None:
            last_tok = parser.diagnose()
            parser.report(InvalidSyntax(parser.get_error_info_on(last_tok)))

        if not errors.ok():
            for issue in errors.issues:
                print(dump_error(issue), file=sys.stderr)
            return
        
        if tree is None:
            return

        print(tree)
        
        if verbose:
            dt = t1 - t0
            last_tok = parser.diagnose()
            nlines = last_tok.get_endpos()[0]
            print(f"Total time: {{dt:.3f}} sec; {{nlines}} lines", end="")
            if dt:
                print(f"; {{nlines / dt:.0f}} lines/sec")
            else:
                print()
            print("Caches sizes:")
            print(f"  token array : {{len(parser._tokenstream._tokens):10}}")
            print(f"        cache : {{len(parser._cache):10}}")
    
    if not filename:
        from .repl import REPL
        REPL(cli).cmdloop("vcs.parser REPL (Read-Eval-Print Loop) module, type Ctrl+C to exit the program")
        exit(0)

    with open(filename, encoding="utf8") as f:
        cli(filename, f.read())



if __name__ == "__main__":
    main()
"""


class GrammarVisitor:
    """
    Base visitor class for traversing grammar AST nodes

    Subclasses implement visit_<NodeType> methods. The visit() method
    dispatches to the appropriate handler or falls back to generic_visit
    """

    def visit(self, node: Any, *args: Any, **kwargs: Any) -> Any:
        """
        Visit a node
        """
        method = "visit_" + type(node).__name__
        visitor = getattr(self, method, self.generic_visit)
        return visitor(node, *args, **kwargs)

    def generic_visit(self, node: Iterable[Any], *args: Any, **kwargs: Any) -> None:
        """
        Called if no explicit visitor function exists for a node
        Iterates over lists and nested nodes
        """
        for value in node:
            if isinstance(value, list):
                for item in value:
                    self.visit(item, *args, **kwargs)
            else:
                self.visit(value, *args, **kwargs)


class GrammarError(Exception):
    pass


class Grammar:
    """
    Represents the entire grammar: mapping of rule names to Rule objects and metadata
    """

    def __init__(self, rules: Iterable[Rule], metas: Iterable[tuple[str, str | None]]):
        self.rules = {rule.name: rule for rule in rules}
        self.metas = dict(metas)

    def __str__(self) -> str:
        return "\n".join(str(rule) for name, rule in self.rules.items())

    def __repr__(self) -> str:
        lines = ["Grammar("]
        lines.append("  [")
        for rule in self.rules.values():
            lines.append(f"    {repr(rule)},")
        lines.append("  ],")
        lines.append("  {repr(list(self.metas.items()))}")
        lines.append(")")
        return "\n".join(lines)

    def __iter__(self) -> Iterator[Rule]:
        yield from self.rules.values()


class Rule:
    """
    A grammar rule

    name: rule name
    type: optional annotation for the AST node type produced
    rhs: the right-hand side (alternatives)
    memo: whether rule should be memoized
    """

    def __init__(
        self, name: str, type: str | None, rhs: Rhs, memo: object | None = None
    ):
        self.name = name
        self.type = type
        self.rhs = rhs
        self.memo = bool(memo)
        self.visited = False
        self.nullable = False
        self.left_recursive = False
        self.leader = False

    def is_loop(self) -> bool:
        return self.name.startswith("loop")

    def is_gather(self) -> bool:
        return self.name.startswith("gather")

    def __str__(self) -> str:
        if SIMPLE_STR or self.type is None:
            res = f"{self.name}: {self.rhs}"
        else:
            res = f"{self.name}[{self.type}]: {self.rhs}"
        if len(res) < 88:
            return res
        lines = [res.split(":")[0] + ":"]
        lines += [f"    | {alt}" for alt in self.rhs.alts]
        return "\n".join(lines)

    def __repr__(self) -> str:
        return f"Rule({self.name!r}, {self.type!r}, {self.rhs!r})"

    def __iter__(self) -> Iterator[Rhs]:
        yield self.rhs

    def initial_names(self) -> set[str]:
        return self.rhs.initial_names()

    def flatten(self) -> Rhs:
        # If it's a single parenthesized group, flatten it
        rhs = self.rhs
        if (
            not self.is_loop()
            and len(rhs.alts) == 1
            and len(rhs.alts[0].items) == 1
            and isinstance(rhs.alts[0].items[0].item, Group)
        ):
            rhs = rhs.alts[0].items[0].item.rhs
        return rhs

    def collect_todo(self, gen: ParserGenerator) -> None:
        rhs = self.flatten()
        rhs.collect_todo(gen)


class Leaf:
    """
    Base class for terminal grammar elements (name or string)
    """

    def __init__(self, value: str):
        self.value = value

    def __str__(self) -> str:
        return self.value

    def __iter__(self):
        if False:
            yield

    def python_expr(self):
        return self.value

    @abstractmethod
    def initial_names(self) -> set[str]:
        raise NotImplementedError


class NameLeaf(Leaf):
    """
    Leaf representing a reference to another rule or a token name
    """

    def __str__(self) -> str:
        if self.value == "ENDMARKER":
            return "$"
        return super().__str__()

    def python_expr(self):
        if self.value in (toktype.name for toktype in TokenType):
            return f"TokenType.{self.value}"
        return super().python_expr()

    def __repr__(self) -> str:
        return f"NameLeaf({self.value!r})"

    def initial_names(self) -> set[str]:
        return {self.value}


class StringLeaf(Leaf):
    """
    Leaf representing a literal string token (including quotes)
    """

    def __repr__(self) -> str:
        return f"StringLeaf({self.value!r})"

    def initial_names(self) -> set[str]:
        return set()


class Rhs:
    """
    Right-hand side: a collection of alternatives (Alt objects)
    """

    def __init__(self, alts: list[Alt]):
        self.alts = alts
        self.memo: tuple[str | None, str] | None = None

    def __str__(self) -> str:
        return " | ".join(str(alt) for alt in self.alts)

    def __repr__(self) -> str:
        return f"Rhs({self.alts!r})"

    def __iter__(self) -> Iterator[list[Alt]]:
        yield self.alts

    def initial_names(self) -> set[str]:
        names: set[str] = set()
        for alt in self.alts:
            names |= alt.initial_names()
        return names

    def collect_todo(self, gen: ParserGenerator) -> None:
        for alt in self.alts:
            alt.collect_todo(gen)


class Alt:
    """
    One alternative in a production; composed of a list of NamedItem
    icut: optional left-cut position (internal)
    action: optional action string attached to the alt
    """

    def __init__(
        self, items: list[NamedItem], *, icut: int = -1, action: str | None = None
    ):
        self.items = items
        self.icut = icut
        self.action = action

    def __str__(self) -> str:
        core = " ".join(str(item) for item in self.items)
        if not SIMPLE_STR and self.action:
            return f"{core} {{ {self.action} }}"
        else:
            return core

    def __repr__(self) -> str:
        args = [repr(self.items)]
        if self.icut >= 0:
            args.append(f"icut={self.icut}")
        if self.action:
            args.append(f"action={self.action!r}")
        return f"Alt({', '.join(args)})"

    def __iter__(self) -> Iterator[list[NamedItem]]:
        yield self.items

    def initial_names(self) -> set[str]:
        names: set[str] = set()
        for item in self.items:
            names |= item.initial_names()
            if not item.nullable:
                break
        return names

    def collect_todo(self, gen: ParserGenerator) -> None:
        for item in self.items:
            item.collect_todo(gen)


class NamedItem:
    """
    An item that may be bound to a name in actions
    """

    def __init__(self, name: str | None, item: Item, type: str | None = None):
        self.name = name
        self.item = item
        self.type = type
        self.nullable = False

    def __str__(self) -> str:
        if not SIMPLE_STR and self.name:
            return f"{self.name}={self.item}"
        else:
            return str(self.item)

    def __repr__(self) -> str:
        return f"NamedItem({self.name!r}, {self.item!r})"

    def __iter__(self) -> Iterator[Item]:
        yield self.item

    def initial_names(self) -> set[str]:
        return self.item.initial_names()

    def collect_todo(self, gen: ParserGenerator) -> None:
        gen.callmakervisitor.visit(self.item)


class Forced:
    """
    Forced lookahead: '&&' operator in grammar (double ampersand)
    """

    def __init__(self, node: Plain):
        self.node = node

    def __str__(self) -> str:
        return f"&&{self.node}"

    def __iter__(self) -> Iterator[Plain]:
        yield self.node

    def initial_names(self) -> set[str]:
        return set()


class Lookahead:
    """
    Base for positive/negative lookahead operators
    sign: textual sign used in pretty printing ('&' or '!')
    """

    def __init__(self, node: Plain, sign: str):
        self.node = node
        self.sign = sign

    def __str__(self) -> str:
        return f"{self.sign}{self.node}"

    def __iter__(self) -> Iterator[Plain]:
        yield self.node

    def initial_names(self) -> set[str]:
        return set()


class PositiveLookahead(Lookahead):
    def __init__(self, node: Plain):
        super().__init__(node, "&")

    def __repr__(self) -> str:
        return f"PositiveLookahead({self.node!r})"


class NegativeLookahead(Lookahead):
    def __init__(self, node: Plain):
        super().__init__(node, "!")

    def __repr__(self) -> str:
        return f"NegativeLookahead({self.node!r})"


class Opt:
    """
    Optional item: either [X] or X? in grammar notation
    """

    def __init__(self, node: Item):
        self.node = node

    def __str__(self) -> str:
        s = str(self.node)
        # TODO: Decide whether to use [X] or X? based on type of X
        if " " in s:
            return f"[{s}]"
        else:
            return f"{s}?"

    def __repr__(self) -> str:
        return f"Opt({self.node!r})"

    def __iter__(self) -> Iterator[Item]:
        yield self.node

    def initial_names(self) -> set[str]:
        return self.node.initial_names()


class Repeat:
    """
    Shared base class for x* and x+ repetition constructs
    """

    def __init__(self, node: Plain):
        self.node = node
        self.memo: tuple[str | None, str] | None = None

    def __iter__(self) -> Iterator[Plain]:
        yield self.node

    def initial_names(self) -> set[str]:
        return self.node.initial_names()


class Repeat0(Repeat):
    def __str__(self) -> str:
        s = str(self.node)
        # TODO: Decide whether to use (X)* or X* based on type of X
        if " " in s:
            return f"({s})*"
        else:
            return f"{s}*"

    def __repr__(self) -> str:
        return f"Repeat0({self.node!r})"


class Repeat1(Repeat):
    def __str__(self) -> str:
        s = str(self.node)
        # TODO: Decide whether to use (X)+ or X+ based on type of X
        if " " in s:
            return f"({s})+"
        else:
            return f"{s}+"

    def __repr__(self) -> str:
        return f"Repeat1({self.node!r})"


class Gather(Repeat):
    """
    Gather represents separated repetition: sep.elem+ notation
    """

    def __init__(self, separator: Plain, node: Plain):
        self.separator = separator
        self.node = node

    def __str__(self) -> str:
        return f"{self.separator!s}.{self.node!s}+"

    def __repr__(self) -> str:
        return f"Gather({self.separator!r}, {self.node!r})"


class Group:
    """
    Parenthesized group in the grammar, e.g. (A B | C)
    """

    def __init__(self, rhs: Rhs):
        self.rhs = rhs

    def __str__(self) -> str:
        return f"({self.rhs})"

    def __repr__(self) -> str:
        return f"Group({self.rhs!r})"

    def __iter__(self) -> Iterator[Rhs]:
        yield self.rhs

    def initial_names(self) -> set[str]:
        return self.rhs.initial_names()


class Cut:
    """
    Cut operator (~) used to prevent backtracking past a point
    """

    def __init__(self) -> None:
        pass

    def __repr__(self) -> str:
        return "Cut()"

    def __str__(self) -> str:
        return "~"

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Cut):
            return NotImplemented
        return True

    def __iter__(self):
        if False:
            yield

    def initial_names(self) -> set[str]:
        return set()


class RuleCheckingVisitor(GrammarVisitor):
    """
    Visitor that validates rule references and variable names in the grammar
    """

    def __init__(self, rules: dict[str, Rule]):
        self.rules = rules

    def visit_NameLeaf(self, node: NameLeaf) -> None:
        if (
            node.value not in self.rules
            and not hasattr(TokenType, node.value)
            and node.value != "ANY"
        ):
            # TODO: Add line/col info to (leaf) nodes
            raise GrammarError(f"Dangling reference to rule {node.value!r}")

    def visit_NamedItem(self, node: NamedItem) -> None:
        if node.name and node.name.startswith("_"):
            raise GrammarError(
                f"Variable names cannot start with underscore: '{node.name}'"
            )
        self.visit(node.item)


class ParserGenerator:
    """
    Base class for generating a parser implementation from a Grammar
    Subclasses must implement generate() to output language specific code
    """

    callmakervisitor: GrammarVisitor

    def __init__(self, grammar: Grammar, file: IO[str]):
        self.grammar = grammar
        self.rules = grammar.rules
        self.validate_rule_names()
        if "trailer" not in grammar.metas and "start" not in self.rules:
            raise GrammarError("Grammar without a trailer must have a 'start' rule")
        checker = RuleCheckingVisitor(self.rules)
        for rule in self.rules.values():
            checker.visit(rule)
        self.file = file
        self.level = 0
        compute_nullables(self.rules)
        self.first_graph, self.first_sccs = compute_left_recursives(self.rules)
        self.todo = self.rules.copy()  # Rules to generate
        self.counter = 0  # For name_rule()/name_loop()
        self.all_rules: dict[str, Rule] = {}  # Rules + temporal rules
        self._local_variable_stack: list[list[str]] = []

    def validate_rule_names(self) -> None:
        for rule in self.rules:
            if rule.startswith("_"):
                raise GrammarError(f"Rule names cannot start with underscore: '{rule}'")

    @contextlib.contextmanager
    def local_variable_context(self) -> Iterator[None]:
        """Manage a stack frame for local variable names used when generating actions."""
        self._local_variable_stack.append([])
        yield
        self._local_variable_stack.pop()

    @property
    def local_variable_names(self) -> list[str]:
        return self._local_variable_stack[-1]

    @abstractmethod
    def generate(self, filename: str, output: str) -> None:
        raise NotImplementedError

    @contextlib.contextmanager
    def indent(self) -> Iterator[None]:
        """Simple indentation context manager for emitted output."""
        self.level += 1
        try:
            yield
        finally:
            self.level -= 1

    def print(self, *args: object) -> None:
        """Print into the target file with current indentation."""
        if not args:
            print(file=self.file)
        else:
            print("    " * self.level, end="", file=self.file)
            print(*args, file=self.file)

    def printblock(self, lines: str) -> None:
        """Print a block of lines preserving internal newlines."""
        for line in lines.splitlines():
            self.print(line)

    def collect_todo(self) -> None:
        """Collects rules (including generated temporary ones) that still need generation."""
        done: set[str] = set()
        while True:
            alltodo = list(self.todo)
            self.all_rules.update(self.todo)
            todo = [i for i in alltodo if i not in done]
            if not todo:
                break
            for rulename in todo:
                self.todo[rulename].collect_todo(self)
            done = set(alltodo)

    def artificial_rule_from_rhs(self, rhs: Rhs) -> str:
        """Create a temporary named rule for a RHS used in expressions."""
        self.counter += 1
        name = f"tmp_{self.counter}"  # TODO: Pick a nicer name
        self.todo[name] = Rule(name, None, rhs)
        return name

    def artificial_rule_from_repeat(self, node: Plain, is_repeat1: bool) -> str:
        """Create a temporary rule implementing repeated constructs."""
        self.counter += 1
        if is_repeat1:
            prefix = "loop1_"
        else:
            prefix = "loop0_"
        name = f"{prefix}{self.counter}"  # TODO: It's ugly to signal via the name
        self.todo[name] = Rule(name, None, Rhs([Alt([NamedItem(None, node)])]))
        return name

    def artificial_rule_from_gather(self, node: Gather) -> str:
        """Create helper rules for gather constructs (separator + repeated items)."""
        self.counter += 1
        name = f"gather_{self.counter}"
        self.counter += 1
        extra_function_name = f"loop0_{self.counter}"
        extra_function_alt = Alt(
            [NamedItem(None, node.separator), NamedItem("elem", node.node)],
            action="elem",
        )
        self.todo[extra_function_name] = Rule(
            extra_function_name,
            None,
            Rhs([extra_function_alt]),
        )
        alt = Alt(
            [
                NamedItem("elem", node.node),
                NamedItem("seq", NameLeaf(extra_function_name)),
            ],
        )
        self.todo[name] = Rule(
            name,
            None,
            Rhs([alt]),
        )
        return name

    def dedupe(self, name: str) -> str:
        """Ensure a generated local variable name does not clash with existing names."""
        origname = name
        counter = 0
        while name in self.local_variable_names:
            counter += 1
            name = f"{origname}_{counter}"
        self.local_variable_names.append(name)
        return name


class NullableVisitor(GrammarVisitor):
    """Visitor to compute nullable (can produce empty) rules/items."""

    def __init__(self, rules: dict[str, Rule]) -> None:
        self.rules = rules
        self.visited: set[Any] = set()

    def visit_Rule(self, rule: Rule) -> bool:
        if rule in self.visited:
            return False
        self.visited.add(rule)
        if self.visit(rule.rhs):
            rule.nullable = True
        return rule.nullable

    def visit_Rhs(self, rhs: Rhs) -> bool:
        for alt in rhs.alts:
            if self.visit(alt):
                return True
        return False

    def visit_Alt(self, alt: Alt) -> bool:
        for item in alt.items:
            if not self.visit(item):
                return False
        return True

    def visit_Forced(self, force: Forced) -> bool:
        return True

    def visit_LookAhead(self, lookahead: Lookahead) -> bool:
        return True

    def visit_Opt(self, opt: Opt) -> bool:
        return True

    def visit_Repeat0(self, repeat: Repeat0) -> bool:
        return True

    def visit_Repeat1(self, repeat: Repeat1) -> bool:
        return False

    def visit_Gather(self, gather: Gather) -> bool:
        return False

    def visit_Cut(self, cut: Cut) -> bool:
        return False

    def visit_Group(self, group: Group) -> bool:
        return self.visit(group.rhs)

    def visit_NamedItem(self, item: NamedItem) -> bool:
        if self.visit(item.item):
            item.nullable = True
        return item.nullable

    def visit_NameLeaf(self, node: NameLeaf) -> bool:
        if node.value in self.rules:
            return self.visit(self.rules[node.value])
        # Token or unknown; never empty
        return False

    def visit_StringLeaf(self, node: StringLeaf) -> bool:
        # The string token '' is considered empty
        return not node.value


def compute_nullables(rules: dict[str, Rule]) -> None:
    """
    Compute which rules in a grammar are nullable
    This populates the Rule.nullable flags using a fixpoint visitor
    """
    nullable_visitor = NullableVisitor(rules)
    for rule in rules.values():
        nullable_visitor.visit(rule)


def compute_left_recursives(
    rules: dict[str, Rule],
) -> tuple[dict[str, set[str]], list[set[str]]]:
    """
    Compute left-recursive rules and SCCs in the invocation graph
    Returns the 'first' graph and the list of strongly connected components
    """
    graph = make_first_graph(rules)
    sccs = list(strongly_connected_components(set(graph.keys()), graph))
    for scc in sccs:
        if len(scc) > 1:
            for name in scc:
                rules[name].left_recursive = True
            # Try to find a leader such that all cycles go through it
            leaders = set(scc)
            for start in scc:
                for cycle in find_cycles_in_scc(graph, scc, start):
                    # print("Cycle:", " -> ".join(cycle))
                    leaders -= scc - set(cycle)
                    if not leaders:
                        raise ValueError(
                            f"SCC {scc} has no leadership candidate (no element is included in all cycles)"
                        )
            # print("Leaders:", leaders)
            leader = min(leaders)  # Pick an arbitrary leader from the candidates
            rules[leader].leader = True
        else:
            name = min(scc)  # The only element
            if name in graph[name]:
                rules[name].left_recursive = True
                rules[name].leader = True
    return graph, sccs


def make_first_graph(rules: dict[str, Rule]) -> dict[str, set[str]]:
    """
    Compute the graph of left-invocations
    There's an edge from A to B if A may invoke B at its initial position
    Note that this requires the nullable flags to have been computed
    """
    graph = {}
    vertices: set[str] = set()
    for rulename, rhs in rules.items():
        graph[rulename] = names = rhs.initial_names()
        vertices |= names
    for vertex in vertices:
        graph.setdefault(vertex, set())
    return graph


def strongly_connected_components(
    vertices: set[str], edges: dict[str, set[str]]
) -> Iterator[set[str]]:
    """
    Compute Strongly Connected Components of a directed graph

    Args:
      vertices: the labels for the vertices
      edges: for each vertex, gives the target vertices of its outgoing edges

    Returns:
      An iterator yielding strongly connected components, each
      represented as a set of vertices.  Each input vertex will occur
      exactly once; vertices not part of a SCC are returned as
      singleton sets

    From http://code.activestate.com/recipes/578507/
    """
    identified: set[str] = set()
    stack: list[str] = []
    index: dict[str, int] = {}
    boundaries: list[int] = []

    def dfs(v: str) -> Iterator[set[str]]:
        index[v] = len(stack)
        stack.append(v)
        boundaries.append(index[v])

        for w in edges[v]:
            if w not in index:
                yield from dfs(w)
            elif w not in identified:
                while index[w] < boundaries[-1]:
                    boundaries.pop()

        if boundaries[-1] == index[v]:
            boundaries.pop()
            scc = set(stack[index[v] :])
            del stack[index[v] :]
            identified.update(scc)
            yield scc

    for v in vertices:
        if v not in index:
            yield from dfs(v)


def find_cycles_in_scc(
    graph: dict[str, set[str]], scc: set[str], start: str
) -> Iterable[list[str]]:
    """
    Find cycles in SCC emanating from start

    Yields lists of the form ['A', 'B', 'C', 'A'], which means there's
    a path from A -> B -> C -> A.  The first item is always the start
    argument, but the last item may be another element, e.g.  ['A',
    'B', 'C', 'B'] means there's a path from A to B and there's a
    cycle from B to C and back
    """
    # Basic input checks
    assert start in scc, (start, scc)
    assert scc <= graph.keys(), scc - graph.keys()

    # Reduce the graph to nodes in the SCC
    graph = {
        src: {dst for dst in dsts if dst in scc}
        for src, dsts in graph.items()
        if src in scc
    }
    assert start in graph

    # Recursive helper that yields cycles
    def dfs(node: str, path: list[str]) -> Iterator[list[str]]:
        if node in path:
            yield path + [node]
            return
        path = path + [node]  # TODO: Make this not quadratic
        for child in graph[node]:
            yield from dfs(child, path)

    yield from dfs(start, [])


def _get_indent_closure() -> Callable[[int], str]:
    _INDENT_CACHE = {}

    def get_indent(level: int) -> str:
        if level not in _INDENT_CACHE:
            _INDENT_CACHE[level] = "  " * level
        return _INDENT_CACHE[level]

    return get_indent


_get_indent = _get_indent_closure()
del _get_indent_closure

def memoize[F: Callable[..., Any], P: GrammarParser](method: F) -> F:
    """
    memoization decorator for grammar parser methods
    """
    method_name = method.__name__

    @wraps(method)
    def memoize_wrapper(self: P, *args: object) -> Any:
        cache = self.cache
        mark = self.mark()
        key = (mark, method_name, args)

        # fast path
        if not self.verbose:
            try:
                tree, endmark = cache[key]
                self.reset(endmark)
                return tree
            except KeyError:
                pass  # continue with slow path
        else:
            # debug path
            cached = cache.get(key)
            if cached is not None:
                tree, endmark = cached
                self.reset(endmark)
                fill = _get_indent(self.level)
                args_repr = ",".join(repr(arg) for arg in args)
                tree_repr = repr(tree)[:80]
                print(f"{fill}{method_name}({args_repr}) -> {tree_repr}\n")
                return tree

        # slow path
        level = self.level

        if self.verbose:
            fill = _get_indent(level)
            args_repr = ",".join(repr(arg) for arg in args)
            peek_repr = repr(self._showpeek())
            print(f"{fill}{method_name}({args_repr}) ... (looking at {peek_repr})\n")

        self.level = level + 1
        try:
            tree = method(self, *args)
        finally:
            self.level = level

        endmark = self.mark()
        cache[key] = (tree, endmark)

        if self.verbose:
            tree_repr = repr(tree)[:80]
            print(f"{fill}... {method_name}({args_repr}) -> {tree_repr}\n")  # type: ignore

        return tree

    return cast(F, memoize_wrapper)


class GrammarTokenizer:
    """
    Caching wrapper for the tokenize module
    """

    _tokens: list[tokenize.TokenInfo]

    def __init__(
        self, tokengen: Iterator[tokenize.TokenInfo], *, path="", verbose=False
    ):
        self.verbose = verbose

        self._tokengen = tokengen
        self._tokens = []
        self._index = 0
        self._lines: dict[int, str] = {}
        self._path = path
        if verbose:
            self.report(False, False)

    def getnext(self) -> tokenize.TokenInfo:
        """Return the next token and updates the index."""
        cached = not self._index == len(self._tokens)
        tok = self.peek()
        self._index += 1
        if self.verbose:
            self.report(cached, False)
        return tok

    def peek(self) -> tokenize.TokenInfo:
        """Return the next token *without* updating the index."""
        while self._index == len(self._tokens):
            tok = next(self._tokengen)
            if tok.type in (tokenize.NL, tokenize.COMMENT):
                continue
            if tok.type == token.ERRORTOKEN and tok.string.isspace():
                continue
            if (
                tok.type == token.NEWLINE
                and self._tokens
                and self._tokens[-1].type == token.NEWLINE
            ):
                continue
            self._tokens.append(tok)
            if not self._path and tok.start[0] not in self._lines:
                self._lines[tok.start[0]] = tok.line
        return self._tokens[self._index]

    def diagnose(self) -> tokenize.TokenInfo:
        if not self._tokens:
            self.getnext()
        return self._tokens[-1]

    def mark(self) -> int:
        return self._index

    def reset(self, index: int) -> None:
        if index == self._index:
            return
        assert 0 <= index <= len(self._tokens), (index, len(self._tokens))
        old_index = self._index
        self._index = index
        if self.verbose:
            self.report(True, index < old_index)

    def report(self, cached: bool, back: bool) -> None:
        if back:
            fill = "-" * self._index + "-"
        elif cached:
            fill = "-" * self._index + ">"
        else:
            fill = "-" * self._index + "*"
        if self._index == 0:
            print(f"{fill} (Bof)")
        else:
            tok = self._tokens[self._index - 1]
            shorttok = "%-25.25s" % f"{tok.start[0]}.{tok.start[1]}: {token.tok_name[tok.type]}:{tok.string!r}"
            print(f"{fill} {shorttok}")


class GrammarParser:
    """
    Parser that reads grammar specification files and builds a Grammar object
    """

    def __init__(
        self,
        filename: str,
        tokenizer: GrammarTokenizer,
        verbose=False,
    ):
        self.diagnose = tokenizer.diagnose
        self.mark = tokenizer.mark
        self.reset = tokenizer.reset
        self.peek = tokenizer.peek
        self.getnext = tokenizer.getnext
        
        self.filename = filename
        self.verbose = verbose
        self.call_invalid_rules = True
        self.level = 0
        self.cache: dict[tuple[int, str, tuple[Any, ...]], tuple[Any, int]] = {}
        self.in_recursive_rule = 0

    @memoize
    def _accept(self, token_type: int | str) -> tokenize.TokenInfo | None:
        """
        Accept a token of the given type or value; returns the TokenInfo or None
        """
        while True:
            mark = self.mark()
            # Get the next tok
            try:
                tok = self.getnext()
            except StopIteration:
                return None

            if tok.type == token_type:
                if token_type == token.NAME and tok.string in self.KEYWORDS:
                    return None
                return tok
                
            elif tok.type == token.NAME and tok.string == token_type:
                return tok
            elif tok.type == token.OP and tok.string == token_type:
                return tok
            else:
                self.reset(mark)
                return None
    
    def _showpeek(self) -> str:
        # brief token display
        tok = self.peek()
        return f"{tok.start[0]}.{tok.start[1]}: {token.tok_name[tok.type]}:{
            tok.string if len(tok.string) <= 64 else tok.string[:64] + '...'
        }"

    def _negative_lookahead(self, func: Callable[..., object], *args: object) -> bool:
        """
        Run func in negative lookahead mode: succeed only if func would fail
        """
        mark = self.mark()
        ok = func(*args)
        self.reset(mark)
        return not ok

    def raise_syntax_error(self, message: str, tok: tokenize.TokenInfo | None = None) -> NoReturn:
        if tok is None:
            tok = self.diagnose()

        info = (self.filename, *tok.start, tok.line, *tok.end)
        raise SyntaxError(message, info)

    @memoize
    def parse(self) -> Grammar | None:
        # start: grammar $
        mark = self.mark()
        if (grammar := self.grammar()) and (self._accept(token.ENDMARKER)):
            return grammar
        self.reset(mark)
        return None

    @memoize
    def grammar(self) -> Grammar | None:
        # grammar: metas rules | rules
        mark = self.mark()
        if (metas := self.metas()) and (rules := self.rules()):
            return Grammar(rules, metas)
        self.reset(mark)
        if rules := self.rules():
            return Grammar(rules, [])
        self.reset(mark)
        return None

    @memoize
    def metas(self) -> MetaList | None:
        # metas: meta metas | meta
        mark = self.mark()
        if (meta := self.meta()) and (metas := self.metas()):
            return [meta] + metas
        self.reset(mark)
        if meta := self.meta():
            return [meta]
        self.reset(mark)
        return None

    @memoize
    def meta(self) -> MetaTuple | None:
        # meta: "@" NAME NEWLINE | "@" NAME NAME NEWLINE | "@" NAME string NEWLINE
        mark = self.mark()
        if (
            (self._accept("@"))
            and (name := self._accept(token.NAME))
            and (self._accept(token.NEWLINE))
        ):
            return (name.string, None)
        self.reset(mark)
        if (
            (self._accept("@"))
            and (a := self._accept(token.NAME))
            and (b := self._accept(token.NAME))
            and (self._accept(token.NEWLINE))
        ):
            return (a.string, b.string)
        self.reset(mark)
        if (
            (self._accept("@"))
            and (name := self._accept(token.NAME))
            and (string := self._accept(token.STRING))
            and (self._accept(token.NEWLINE))
        ):
            return (name.string, ast.literal_eval(string.string))
        self.reset(mark)
        return None

    @memoize
    def rules(self) -> RuleList | None:
        # rules: rule rules | rule
        mark = self.mark()
        if (rule := self.rule()) and (rules := self.rules()):
            return [rule] + rules
        self.reset(mark)
        if rule := self.rule():
            return [rule]
        self.reset(mark)
        return None

    @memoize
    def rule(self) -> Rule | None:
        # rule: rulename memoflag? ":" alts NEWLINE INDENT more_alts DEDENT | rulename memoflag? ":" NEWLINE INDENT more_alts DEDENT | rulename memoflag? ":" alts NEWLINE
        mark = self.mark()
        if (
            (rulename := self.rulename())
            and (opt := self.memoflag(),)
            and (self._accept(":"))
            and (alts := self.alts())
            and (self._accept(token.NEWLINE))
            and (self._accept(token.INDENT))
            and (more_alts := self.more_alts())
            and (self._accept(token.DEDENT))
        ):
            return Rule(
                rulename[0], rulename[1], Rhs(alts.alts + more_alts.alts), memo=opt
            )
        self.reset(mark)
        if (
            (rulename := self.rulename())
            and (opt := self.memoflag(),)
            and (self._accept(":"))
            and (self._accept(token.NEWLINE))
            and (self._accept(token.INDENT))
            and (more_alts := self.more_alts())
            and (self._accept(token.DEDENT))
        ):
            return Rule(rulename[0], rulename[1], more_alts, memo=opt)
        self.reset(mark)
        if (
            (rulename := self.rulename())
            and (opt := self.memoflag(),)
            and (self._accept(":"))
            and (alts := self.alts())
            and (self._accept(token.NEWLINE))
        ):
            return Rule(rulename[0], rulename[1], alts, memo=opt)
        self.reset(mark)
        return None

    @memoize
    def rulename(self) -> RuleName | tuple[str, None] | None:
        # rulename: NAME annotation | NAME
        mark = self.mark()
        if (name := self._accept(token.NAME)) and (annotation := self.annotation()):
            return (name.string, annotation)
        self.reset(mark)
        if name := self._accept(token.NAME):
            return (name.string, None)
        self.reset(mark)
        return None

    @memoize
    def memoflag(self) -> str | None:
        # memoflag: '(' "memo" ')'
        mark = self.mark()
        if (self._accept("(")) and (self._accept("memo")) and (self._accept(")")):
            return "memo"
        self.reset(mark)
        return None

    @memoize
    def alts(self) -> Rhs | None:
        # alts: alt "|" alts | alt
        mark = self.mark()
        if (alt := self.alt()) and (self._accept("|")) and (alts := self.alts()):
            return Rhs([alt] + alts.alts)
        self.reset(mark)
        if alt := self.alt():
            return Rhs([alt])
        self.reset(mark)
        return None

    @memoize
    def more_alts(self) -> Rhs | None:
        # more_alts: "|" alts NEWLINE more_alts | "|" alts NEWLINE
        mark = self.mark()
        if (
            (self._accept("|"))
            and (alts := self.alts())
            and (self._accept(token.NEWLINE))
            and (more_alts := self.more_alts())
        ):
            return Rhs(alts.alts + more_alts.alts)
        self.reset(mark)
        if (
            (self._accept("|"))
            and (alts := self.alts())
            and (self._accept(token.NEWLINE))
        ):
            return Rhs(alts.alts)
        self.reset(mark)
        return None

    @memoize
    def alt(self) -> Alt | None:
        # alt: items '$' action | items '$' | items action | items
        mark = self.mark()
        if (
            (items := self.items())
            and (self._accept("$"))
            and (action := self.action())
        ):
            return Alt(items + [NamedItem(None, NameLeaf("ENDMARKER"))], action=action)
        self.reset(mark)
        if (items := self.items()) and (self._accept("$")):
            return Alt(items + [NamedItem(None, NameLeaf("ENDMARKER"))], action=None)
        self.reset(mark)
        if (items := self.items()) and (action := self.action()):
            return Alt(items, action=action)
        self.reset(mark)
        if items := self.items():
            return Alt(items, action=None)
        self.reset(mark)
        return None

    @memoize
    def items(self) -> NamedItemList | None:
        # items: named_item items | named_item
        mark = self.mark()
        if (named_item := self.named_item()) and (items := self.items()):
            return [named_item] + items
        self.reset(mark)
        if named_item := self.named_item():
            return [named_item]
        self.reset(mark)
        return None

    @memoize
    def named_item(self) -> NamedItem | None:
        # named_item: NAME annotation '=' ~ item | NAME '=' ~ item | item | forced_atom | lookahead
        mark = self.mark()
        cut = False
        if (
            (name := self._accept(token.NAME))
            and (annotation := self.annotation())
            and (self._accept("="))
            and (cut := True)
            and (item := self.item())
        ):
            return NamedItem(name.string, item, annotation)
        self.reset(mark)
        if cut:
            return None
        cut = False
        if (
            (name := self._accept(token.NAME))
            and (self._accept("="))
            and (cut := True)
            and (item := self.item())
        ):
            return NamedItem(name.string, item)
        self.reset(mark)
        if cut:
            return None
        if item := self.item():
            return NamedItem(None, item)
        self.reset(mark)
        if it := self.forced_atom():
            return NamedItem(None, it)
        self.reset(mark)
        if it := self.lookahead():
            return NamedItem(None, it)
        self.reset(mark)
        return None

    @memoize
    def forced_atom(self) -> LookaheadOrCut | None:
        # forced_atom: '&' '&' ~ atom
        mark = self.mark()
        cut = False
        if (
            (self._accept("&"))
            and (self._accept("&"))
            and (cut := True)
            and (atom := self.atom())
        ):
            return Forced(atom)
        self.reset(mark)
        if cut:
            return None
        return None

    @memoize
    def lookahead(self) -> LookaheadOrCut | None:
        # lookahead: '&' ~ atom | '!' ~ atom | '~'
        mark = self.mark()
        cut = False
        if (self._accept("&")) and (cut := True) and (atom := self.atom()):
            return PositiveLookahead(atom)
        self.reset(mark)
        if cut:
            return None
        cut = False
        if (self._accept("!")) and (cut := True) and (atom := self.atom()):
            return NegativeLookahead(atom)
        self.reset(mark)
        if cut:
            return None
        if self._accept("~"):
            return Cut()
        self.reset(mark)
        return None

    @memoize
    def item(self) -> Item | None:
        # item: '[' ~ alts ']' | atom '?' | atom '*' | atom '+' | atom '.' atom '+' | atom
        mark = self.mark()
        cut = False
        if (
            (self._accept("["))
            and (cut := True)
            and (alts := self.alts())
            and (self._accept("]"))
        ):
            return Opt(alts)
        self.reset(mark)
        if cut:
            return None
        if (atom := self.atom()) and (self._accept("?")):
            return Opt(atom)
        self.reset(mark)
        if (atom := self.atom()) and (self._accept("*")):
            return Repeat0(atom)
        self.reset(mark)
        if (atom := self.atom()) and (self._accept("+")):
            return Repeat1(atom)
        self.reset(mark)
        if (
            (sep := self.atom())
            and (self._accept("."))
            and (node := self.atom())
            and (self._accept("+"))
        ):
            return Gather(sep, node)
        self.reset(mark)
        if atom := self.atom():
            return atom
        self.reset(mark)
        return None

    @memoize
    def atom(self) -> Plain | None:
        # atom: '(' ~ alts ')' | NAME | string
        mark = self.mark()
        cut = False
        if (
            (self._accept("("))
            and (cut := True)
            and (alts := self.alts())
            and (self._accept(")"))
        ):
            return Group(alts)
        self.reset(mark)
        if cut:
            return None
        if name := self._accept(token.NAME):
            return NameLeaf(name.string)
        self.reset(mark)
        if string := self._accept(token.STRING):
            return StringLeaf(string.string)
        self.reset(mark)
        return None

    @memoize
    def action(self) -> str | None:
        # action: "{" ~ target_atoms "}"
        mark = self.mark()
        cut = False
        if (
            (self._accept("{"))
            and (cut := True)
            and (target_atoms := self.target_atoms())
            and (self._accept("}"))
        ):
            return target_atoms
        self.reset(mark)
        if cut:
            return None
        return None

    @memoize
    def annotation(self) -> str | None:
        # annotation: "[" ~ target_atoms "]"
        mark = self.mark()
        cut = False
        if (
            (self._accept("["))
            and (cut := True)
            and (target_atoms := self.target_atoms())
            and (self._accept("]"))
        ):
            return target_atoms
        self.reset(mark)
        if cut:
            return None
        return None

    @memoize
    def target_atoms(self) -> str | None:
        # target_atoms: target_atom target_atoms | target_atom
        mark = self.mark()
        if (target_atom := self.target_atom()) and (
            target_atoms := self.target_atoms()
        ):
            return target_atom + " " + target_atoms
        self.reset(mark)
        if target_atom := self.target_atom():
            return target_atom
        self.reset(mark)
        return None

    @memoize
    def target_atom(self) -> str | None:
        # target_atom: "{" ~ target_atoms? "}" | "[" ~ target_atoms? "]" | NAME "*" | NAME | NUMBER | STRING | FSTRING_START target_fstring_middle* FSTRING_END | "?" | ":" | !"}" !"]" OP
        mark = self.mark()
        cut = False
        if (
            (self._accept("{"))
            and (cut := True)
            and (atoms := self.target_atoms(),)
            and (self._accept("}"))
        ):
            return "{" + (atoms or "") + "}"
        self.reset(mark)
        if cut:
            return None
        cut = False
        if (
            (self._accept("["))
            and (cut := True)
            and (atoms := self.target_atoms(),)
            and (self._accept("]"))
        ):
            return "[" + (atoms or "") + "]"
        self.reset(mark)
        if cut:
            return None
        if (name := self._accept(token.NAME)) and (self._accept("*")):
            return name.string + "*"
        self.reset(mark)
        if name := self._accept(token.NAME):
            return name.string
        self.reset(mark)
        if int := self._accept(token.NUMBER):
            return int.string
        self.reset(mark)
        if string := self._accept(token.STRING):
            return string.string
        self.reset(mark)
        if (l := self._accept("FSTRING_START")) and (m := self._loop0_1(),) and (r := self._accept("FSTRING_END")):
            return l.string + "".join(m) + r.string
        self.reset(mark)
        if self._accept("?"):
            return "?"
        self.reset(mark)
        if self._accept(":"):
            return ":"
        self.reset(mark)
        if (
            (self._negative_lookahead(self._accept, "}"))
            and (self._negative_lookahead(self._accept, "]"))
            and (op := self._accept(token.OP))
        ):
            return op.string
        self.reset(mark)
        return None

    @memoize
    def target_fstring_middle(self) -> str | None:
        # target_fstring_middle: FSTRING_MIDDLE | "{" | "}" | target_atom
        mark = self.mark()
        if fstring_middle := self._accept("FSTRING_MIDDLE"):
            return fstring_middle.string
        self.reset(mark)
        if self._accept("{"):
            return "{"
        self.reset(mark)
        if self._accept("}"):
            return "}"
        self.reset(mark)
        if target_atom := self.target_atom():
            return target_atom
        self.reset(mark)
        return None

    @memoize
    def _loop0_1(self) -> Any:
        # _loop0_1: target_fstring_middle
        mark = self.mark()
        children = []
        while target_fstring_middle := self.target_fstring_middle():
            children.append(target_fstring_middle)
            mark = self.mark()
        self.reset(mark)
        return children

    KEYWORDS = ()
    SOFT_KEYWORDS = ("memo",)


class InvalidNodeVisitor(GrammarVisitor):
    """
    Detect nodes that are marked 'invalid...' for unreachable/diagnostic purposes
    """

    def visit_NameLeaf(self, node: NameLeaf) -> bool:
        name = node.value
        return name.startswith("invalid")

    def visit_StringLeaf(self, node: StringLeaf) -> bool:
        return False

    def visit_NamedItem(self, node: NamedItem) -> bool:
        return self.visit(node.item)

    def visit_Rhs(self, node: Rhs) -> bool:
        return any(self.visit(alt) for alt in node.alts)

    def visit_Alt(self, node: Alt) -> bool:
        return any(self.visit(item) for item in node.items)

    def lookahead_call_helper(self, node: Lookahead) -> bool:
        return self.visit(node.node)

    def visit_PositiveLookahead(self, node: PositiveLookahead) -> bool:
        return self.lookahead_call_helper(node)

    def visit_NegativeLookahead(self, node: NegativeLookahead) -> bool:
        return self.lookahead_call_helper(node)

    def visit_Opt(self, node: Opt) -> bool:
        return self.visit(node.node)

    def visit_Repeat(self, node: Repeat0) -> tuple[str, str]:
        return self.visit(node.node)

    def visit_Gather(self, node: Gather) -> tuple[str, str]:
        return self.visit(node.node)

    def visit_Group(self, node: Group) -> bool:
        return self.visit(node.rhs)

    def visit_Cut(self, node: Cut) -> bool:
        return False

    def visit_Forced(self, node: Forced) -> bool:
        return self.visit(node.node)


class PythonCallMakerVisitor(GrammarVisitor):
    """
    Build Python call expressions for grammar elements

    Produces (name, call) pairs where 'call' is a Python snippet invoking
    the corresponding parser method/token acceptor
    """

    def __init__(self, parser_generator: ParserGenerator):
        self.gen = parser_generator
        self.cache: dict[Any, Any] = {}
        self.keywords: set[str] = set()
        self.soft_keywords: set[str] = set()

    def visit_NameLeaf(self, node: NameLeaf) -> tuple[str | None, str]:
        name = node.value
        if name == "SOFT_KEYWORD":
            return "soft_keyword", 'self._accept("SOFT_KEYWORD")'
        if name == "ANY":
            return None, "self._getnext()"
        if hasattr(TokenType, name):
            return name.lower(), f"self._accept({node.python_expr()})"
        return name, f"self._{name}()"

    def visit_StringLeaf(self, node: StringLeaf) -> tuple[str, str]:
        val = ast.literal_eval(node.value)
        if re.match(r"[a-zA-Z_]\w*\Z", val):  # This is a keyword
            if node.value.startswith("'"):
                self.keywords.add(val)
            else:
                self.soft_keywords.add(val)
        return "literal", f"self._accept({node.python_expr()})"

    def visit_Rhs(self, node: Rhs) -> tuple[str | None, str]:
        if node in self.cache:
            return self.cache[node]
        if len(node.alts) == 1 and len(node.alts[0].items) == 1:
            self.cache[node] = self.visit(node.alts[0].items[0])
        else:
            name = self.gen.artificial_rule_from_rhs(node)
            self.cache[node] = name, f"self._{name}()"
        return self.cache[node]

    def visit_NamedItem(self, node: NamedItem) -> tuple[str | None, str]:
        name, call = self.visit(node.item)
        if node.name:
            name = node.name
        return name, call

    def lookahead_call_helper(self, node: Lookahead) -> tuple[str, str]:
        name, call = self.visit(node.node)
        head, tail = call.split("(", 1)
        assert tail[-1] == ")"
        tail = tail[:-1]
        return head, tail

    def visit_PositiveLookahead(self, node: PositiveLookahead) -> tuple[None, str]:
        head, tail = self.lookahead_call_helper(node)
        return None, f"self._positive_lookahead({head}, {tail})"

    def visit_NegativeLookahead(self, node: NegativeLookahead) -> tuple[None, str]:
        head, tail = self.lookahead_call_helper(node)
        return None, f"self._negative_lookahead({head}, {tail})"

    def visit_Opt(self, node: Opt) -> tuple[str, str]:
        name, call = self.visit(node.node)
        # Note trailing comma (the call may already have one comma
        # at the end, for example when rules have both repeat0 and optional
        # markers, e.g: [rule*])
        if call.endswith(","):
            return "opt", call
        else:
            return "opt", f"{call},"

    def visit_Repeat0(self, node: Repeat0) -> tuple[str, str]:
        if node in self.cache:
            return self.cache[node]
        name = self.gen.artificial_rule_from_repeat(node.node, False)
        self.cache[node] = name, f"self._{name}(),"  # Also a trailing comma!
        return self.cache[node]

    def visit_Repeat1(self, node: Repeat1) -> tuple[str, str]:
        if node in self.cache:
            return self.cache[node]
        name = self.gen.artificial_rule_from_repeat(node.node, True)
        self.cache[node] = name, f"self._{name}()"  # But no trailing comma here!
        return self.cache[node]

    def visit_Gather(self, node: Gather) -> tuple[str, str]:
        if node in self.cache:
            return self.cache[node]
        name = self.gen.artificial_rule_from_gather(node)
        self.cache[node] = name, f"self._{name}()"  # No trailing comma here either!
        return self.cache[node]

    def visit_Group(self, node: Group) -> tuple[str | None, str]:
        return self.visit(node.rhs)

    def visit_Cut(self, node: Cut) -> tuple[str, str]:
        return "cut", "True"

    def visit_Forced(self, node: Forced) -> tuple[str, str]:
        if isinstance(node.node, Group):
            _, val = self.visit(node.node.rhs)
            return "forced", f"self._expect({val}, '''({node.node.rhs!s})''')"
        else:
            return (
                "forced",
                f"self._expect(self._accept({node.node.python_expr()}), {node.node.python_expr()})",
            )


class UsedNamesVisitor(ast.NodeVisitor):
    """
    AST visitor used to collect all Name nodes inside parsed action code
    """

    def generic_visit(self, node: ast.AST) -> set[str]:
        result = set()
        for _, value in ast.iter_fields(node):
            if isinstance(value, list):
                for item in value:
                    if isinstance(item, ast.AST):
                        result.update(self.visit(item))
            elif isinstance(value, ast.AST):
                result.update(self.visit(value))
        return result

    def visit_Name(self, node: ast.Name) -> set[str]:
        return {node.id}


class PythonParserGenerator(ParserGenerator, GrammarVisitor):
    """
    Generate Python parser source code from a Grammar object
    Responsible for emitting the parser class, methods for each rule, and
    wiring up keyword/soft-keyword sets
    """

    def __init__(
        self,
        grammar: Grammar,
        file: IO[str],
        location_formatting: str | None = None,
        unreachable_formatting: str | None = None,
    ):
        super().__init__(grammar, file)
        self.callmakervisitor: PythonCallMakerVisitor = PythonCallMakerVisitor(self)  # type: ignore
        self.invalidvisitor: InvalidNodeVisitor = InvalidNodeVisitor()
        self.usednamesvisitor: UsedNamesVisitor = UsedNamesVisitor()
        self.unreachable_formatting = (
            unreachable_formatting or "None  # type: ignore"
        )
        self.location_formatting = (
            location_formatting
            or "\nfilename=self.filename, lineno=start_lineno, column=start_column, end_lineno=end_lineno, end_column=end_column"
        )
        self.cleanup_statements: list[str] = []

    def generate(self, filename: str, output: str) -> None:
        header = self.grammar.metas.get("header") or MODULE_PREFIX
        cls_name = self.grammar.metas.get("class") or "GeneratedParser"
        subheader = self.grammar.metas.get("subheader") or ""
        fallback = self.grammar.metas.get("fallback") or "None"

        self.print(header.rstrip().format(
            filename=filename, output=output, class_name=cls_name, subheader=subheader, fallback=fallback
        ))
        while self.todo:
            for rulename, rule in list(self.todo.items()):
                del self.todo[rulename]
                self.print("")
                with self.indent():
                    self.visit(rule)

        self.print()
        with self.indent():
            self.print(f"KEYWORDS = {tuple(sorted(self.callmakervisitor.keywords))}")
            self.print(f"SOFT_KEYWORDS = {tuple(sorted(self.callmakervisitor.soft_keywords))}")

        trailer = (
            self.grammar.metas.get("trailer")
            or MODULE_SUFFIX.format(filename=filename, output=output, class_name=cls_name)
        )
        self.print(trailer.rstrip("\n"))

    def alts_uses_locations(self, alts: list[Alt]) -> bool:
        """Return True if any alternative references LOCATIONS for span information."""
        for alt in alts:
            if alt.action and "LOCATIONS" in alt.action:
                return True
            for n in alt.items:
                if isinstance(n.item, Group) and self.alts_uses_locations(
                    n.item.rhs.alts
                ):
                    return True
        return False

    def add_return(self, ret_val: str) -> None:
        """Emit cleanup statements and a return statement."""
        for stmt in self.cleanup_statements:
            self.print(stmt)
        self.print(f"return {ret_val}")

    def visit_Rule(self, node: Rule) -> None:
        is_loop = node.is_loop()
        is_gather = node.is_gather()
        rhs = node.flatten()
        if node.left_recursive:
            if node.leader:
                self.print("@memoize_left_rec")
            else:
                # Non-leader rules in a cycle are not memoized,
                # but they must still be logged
                self.print("@logger")
        else:
            self.print("@memoize")
        node_type = node.type or "Any"
        if is_loop:
            node_type = f"list[{node_type}]"
        else:
            node_type = f"{node_type} | None"

        name = f"_{node.name}"
        self.print(f"def {name}(self) -> {node_type}:")
        with self.indent():
            # Append an underscore when the name is 'type' so it won't be treated as type comment
            node_name = "type_" if node.name == "type" else node.name
            self.print(f"# {node_name}: {rhs}")
            if node.nullable:
                self.print(f"# nullable={node.nullable}")

            if node.name.endswith("without_invalid"):
                self.print("_prev_call_invalid = self._call_invalid_rules")
                self.print("self._call_invalid_rules = False")
                self.cleanup_statements.append(
                    "self._call_invalid_rules = _prev_call_invalid"
                )
            self.print("mark = self._mark()")
            if self.alts_uses_locations(node.rhs.alts):
                self.print("tok = self._peek()")
                self.print("start_lineno, start_column = tok.lineno, tok.column")
            if is_loop:
                self.print("children = []")
            self.visit(rhs, is_loop=is_loop, is_gather=is_gather)
            if is_loop:
                self.add_return("children")
            else:
                self.add_return("None")

        if node.name.endswith("without_invalid"):
            self.cleanup_statements.pop()

    def visit_NamedItem(
        self, node: NamedItem, used: set[str] | None, unreachable: bool
    ) -> None:
        """Emit code for a named item, possibly binding its value to a variable."""
        name, call = self.callmakervisitor.visit(node.item)
        if unreachable:
            name = None
        elif node.name:
            name = node.name

        if used is not None and name not in used:
            name = None

        if not name:
            # Parentheses are needed because the trailing comma may appear :>
            self.print(f"({call})")
        else:
            if name != "cut":
                name = self.dedupe(name)
            self.print(f"({name} := {call})")

    def visit_Rhs(
        self, node: Rhs, is_loop: bool = False, is_gather: bool = False
    ) -> None:
        if is_loop:
            assert len(node.alts) == 1
        for alt in node.alts:
            self.visit(alt, is_loop=is_loop, is_gather=is_gather)

    def print_action(
        self,
        action: str | None,
        locations: bool,
        unreachable: bool,
        is_gather: bool,
        is_loop: bool,
        has_invalid: bool,
    ) -> None:
        """Emit the action code for a matched alternative (or default behavior)."""
        if not action:
            if is_gather:
                assert len(self.local_variable_names) == 2
                action = (
                    f"[{self.local_variable_names[0]}] + {self.local_variable_names[1]}"
                )
            else:
                if has_invalid:
                    assert unreachable
                    assert isinstance(action, str)  # for type checker
                elif len(self.local_variable_names) == 1:
                    action = f"{self.local_variable_names[0]}"
                else:
                    action = f"[{', '.join(self.local_variable_names)}]"

        if locations:
            self.print("tok = self._last_nonblank_token()")
            self.print("end_lineno, end_column = tok.end_lineno, tok.end_column")

        if is_loop:
            self.print(f"children.append({action})")
            self.print("mark = self._mark()")
        else:
            self.add_return(f"{action}")

    def visit_Alt(self, node: Alt, is_loop: bool, is_gather: bool) -> None:
        """Emit code for an alternative: condition test and action on success."""
        has_cut = any(isinstance(item.item, Cut) for item in node.items)
        has_invalid = self.invalidvisitor.visit(node)

        action = node.action
        if not action and not is_gather and has_invalid:
            action = "UNREACHABLE"

        locations = False
        unreachable = False
        used = None
        if action:
            # Replace magic name in the action rule
            if "LOCATIONS" in action:
                locations = True
                action = action.replace("LOCATIONS", self.location_formatting)
            if "UNREACHABLE" in action:
                unreachable = True
                action = action.replace("UNREACHABLE", self.unreachable_formatting)

            parsed_action = ast.parse(action)
            # Extract the names actually used in the action
            used = self.usednamesvisitor.visit(parsed_action)
            if has_cut:
                used.add("cut")
            action = ast.unparse(parsed_action)

        with self.local_variable_context():
            if has_cut:
                self.print("cut = False")
            if is_loop:
                self.print("while (")
            else:
                self.print("if (")
            with self.indent():
                first = True
                if has_invalid:
                    self.print("self._call_invalid_rules")
                    first = False
                for item in node.items:
                    if first:
                        first = False
                    else:
                        self.print("and")
                    self.visit(item, used=used, unreachable=unreachable)
                    if is_gather:
                        self.print("is not None")

            self.print("):")
            with self.indent():
                # flake8 complains that visit_Alt is too complicated, so here we are :P
                self.print_action(
                    action, locations, unreachable, is_gather, is_loop, has_invalid
                )

            self.print("self._reset(mark)")
            # Skip remaining alternatives if a cut was reached
            if has_cut:
                self.print("if cut:")
                with self.indent():
                    self.add_return("None")


def generate_parser(
    grammar_file: str, output_file: str, verbose=False
) -> tuple[Grammar, GrammarParser, GrammarTokenizer, ParserGenerator]:
    """Convenience function: parse a grammar file and write a generated parser file."""
    with open(grammar_file, encoding="utf8") as f:
        tokgen = tokenize.generate_tokens(f.readline)
        tokenstream = GrammarTokenizer(tokgen, path=grammar_file, verbose=verbose)
        parser = GrammarParser(grammar_file, tokenstream, verbose)
        grammar = parser.parse()

    if not grammar:
        parser.raise_syntax_error("Invalid grammar")

    with open(output_file, "w") as file:
        gen = PythonParserGenerator(grammar, file)
        gen.generate(grammar_file, output_file)
    return grammar, parser, tokenstream, gen


def main() -> None:
    argparser = argparse.ArgumentParser(
        prog="python -m vcs.pegen", description="PEG-like parser generator"
    )
    argparser.add_argument(
        "-q", "--quiet", action="store_true", help="Don't print the parsed grammar"
    )
    argparser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Print timing stats; repeat for more debug output",
    )

    argparser.add_argument("filename", help="Grammar description")
    argparser.add_argument(
        "-o",
        "--output",
        metavar="OUT",
        default="parse.py",
        help="Where to write the generated parser",
    )

    args = argparser.parse_args()

    t0 = time.time()
    grammar, parser, tokenstream, gen = generate_parser(
        args.filename, args.output, args.verbose
    )
    t1 = time.time()

    if args.verbose:
        print("First Graph:")
        for src, dsts in gen.first_graph.items():
            print(f"  {src} -> {', '.join(dsts)}")
        print("First SCCS:")
        for scc in gen.first_sccs:
            print(" ", scc, end="")
            if len(scc) > 1:
                print(
                    "  # Indirectly left-recursive; leaders:",
                    {name for name in scc if grammar.rules[name].leader},
                )
            else:
                name = next(iter(scc))
                if name in gen.first_graph[name]:
                    print("  # Left-recursive")
                else:
                    print()

        dt = t1 - t0
        last_tok = tokenstream.diagnose()
        nlines = last_tok.end[0]
        print(f"Total time: {dt:.3f} sec; {nlines} lines", end="")
        if dt:
            print(f"; {nlines / dt:.0f} lines/sec")
        else:
            print()
        print("Caches sizes:")
        print(f"  token array : {len(tokenstream._tokens):10}")
        print(f"        cache : {len(parser.cache):10}")


if __name__ == "__main__":
    main()
